var annotated_dup =
[
    [ "music_theory", "namespacemusic__theory.html", [
      [ "Transposer", "classmusic__theory_1_1Transposer.html", "classmusic__theory_1_1Transposer" ]
    ] ],
    [ "musx", "namespacemusx.html", [
      [ "dom", "namespacemusx_1_1dom.html", [
        [ "details", "namespacemusx_1_1dom_1_1details.html", [
          [ "AccidentalAlterations", "classmusx_1_1dom_1_1details_1_1AccidentalAlterations.html", "classmusx_1_1dom_1_1details_1_1AccidentalAlterations" ],
          [ "ArticulationAssign", "classmusx_1_1dom_1_1details_1_1ArticulationAssign.html", "classmusx_1_1dom_1_1details_1_1ArticulationAssign" ],
          [ "Baseline", "classmusx_1_1dom_1_1details_1_1Baseline.html", "classmusx_1_1dom_1_1details_1_1Baseline" ],
          [ "BaselineChords", "classmusx_1_1dom_1_1details_1_1BaselineChords.html", "classmusx_1_1dom_1_1details_1_1BaselineChords" ],
          [ "BaselineExpressionsAbove", "classmusx_1_1dom_1_1details_1_1BaselineExpressionsAbove.html", "classmusx_1_1dom_1_1details_1_1BaselineExpressionsAbove" ],
          [ "BaselineExpressionsBelow", "classmusx_1_1dom_1_1details_1_1BaselineExpressionsBelow.html", "classmusx_1_1dom_1_1details_1_1BaselineExpressionsBelow" ],
          [ "BaselineFretboards", "classmusx_1_1dom_1_1details_1_1BaselineFretboards.html", "classmusx_1_1dom_1_1details_1_1BaselineFretboards" ],
          [ "BaselineLyricsChorus", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus" ],
          [ "BaselineLyricsSection", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection" ],
          [ "BaselineLyricsVerse", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse" ],
          [ "BaselineNoInci", "classmusx_1_1dom_1_1details_1_1BaselineNoInci.html", "classmusx_1_1dom_1_1details_1_1BaselineNoInci" ],
          [ "BaselineSystemChords", "classmusx_1_1dom_1_1details_1_1BaselineSystemChords.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemChords" ],
          [ "BaselineSystemExpressionsAbove", "classmusx_1_1dom_1_1details_1_1BaselineSystemExpressionsAbove.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemExpressionsAbove" ],
          [ "BaselineSystemExpressionsBelow", "classmusx_1_1dom_1_1details_1_1BaselineSystemExpressionsBelow.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemExpressionsBelow" ],
          [ "BaselineSystemFretboards", "classmusx_1_1dom_1_1details_1_1BaselineSystemFretboards.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemFretboards" ],
          [ "BaselineSystemLyricsChorus", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsChorus.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsChorus" ],
          [ "BaselineSystemLyricsSection", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsSection.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsSection" ],
          [ "BaselineSystemLyricsVerse", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsVerse.html", "classmusx_1_1dom_1_1details_1_1BaselineSystemLyricsVerse" ],
          [ "BeamAlterations", "classmusx_1_1dom_1_1details_1_1BeamAlterations.html", "classmusx_1_1dom_1_1details_1_1BeamAlterations" ],
          [ "BeamAlterationsDownStem", "classmusx_1_1dom_1_1details_1_1BeamAlterationsDownStem.html", "classmusx_1_1dom_1_1details_1_1BeamAlterationsDownStem" ],
          [ "BeamAlterationsUpStem", "classmusx_1_1dom_1_1details_1_1BeamAlterationsUpStem.html", "classmusx_1_1dom_1_1details_1_1BeamAlterationsUpStem" ],
          [ "BeamExtension", "classmusx_1_1dom_1_1details_1_1BeamExtension.html", "classmusx_1_1dom_1_1details_1_1BeamExtension" ],
          [ "BeamExtensionDownStem", "classmusx_1_1dom_1_1details_1_1BeamExtensionDownStem.html", "classmusx_1_1dom_1_1details_1_1BeamExtensionDownStem" ],
          [ "BeamExtensionUpStem", "classmusx_1_1dom_1_1details_1_1BeamExtensionUpStem.html", "classmusx_1_1dom_1_1details_1_1BeamExtensionUpStem" ],
          [ "BeamStubDirection", "classmusx_1_1dom_1_1details_1_1BeamStubDirection.html", "classmusx_1_1dom_1_1details_1_1BeamStubDirection" ],
          [ "Bracket", "classmusx_1_1dom_1_1details_1_1Bracket.html", "classmusx_1_1dom_1_1details_1_1Bracket" ],
          [ "CenterShape", "classmusx_1_1dom_1_1details_1_1CenterShape.html", "classmusx_1_1dom_1_1details_1_1CenterShape" ],
          [ "ChordAssign", "classmusx_1_1dom_1_1details_1_1ChordAssign.html", "classmusx_1_1dom_1_1details_1_1ChordAssign" ],
          [ "ClefOctaveFlats", "classmusx_1_1dom_1_1details_1_1ClefOctaveFlats.html", "classmusx_1_1dom_1_1details_1_1ClefOctaveFlats" ],
          [ "ClefOctaveSharps", "classmusx_1_1dom_1_1details_1_1ClefOctaveSharps.html", "classmusx_1_1dom_1_1details_1_1ClefOctaveSharps" ],
          [ "CrossStaff", "classmusx_1_1dom_1_1details_1_1CrossStaff.html", "classmusx_1_1dom_1_1details_1_1CrossStaff" ],
          [ "CustomDownStem", "classmusx_1_1dom_1_1details_1_1CustomDownStem.html", "classmusx_1_1dom_1_1details_1_1CustomDownStem" ],
          [ "CustomStem", "classmusx_1_1dom_1_1details_1_1CustomStem.html", "classmusx_1_1dom_1_1details_1_1CustomStem" ],
          [ "CustomUpStem", "classmusx_1_1dom_1_1details_1_1CustomUpStem.html", "classmusx_1_1dom_1_1details_1_1CustomUpStem" ],
          [ "DotAlterations", "classmusx_1_1dom_1_1details_1_1DotAlterations.html", "classmusx_1_1dom_1_1details_1_1DotAlterations" ],
          [ "EntryPartFieldDetail", "classmusx_1_1dom_1_1details_1_1EntryPartFieldDetail.html", "classmusx_1_1dom_1_1details_1_1EntryPartFieldDetail" ],
          [ "EntrySize", "classmusx_1_1dom_1_1details_1_1EntrySize.html", "classmusx_1_1dom_1_1details_1_1EntrySize" ],
          [ "FretboardDiagram", "classmusx_1_1dom_1_1details_1_1FretboardDiagram.html", "classmusx_1_1dom_1_1details_1_1FretboardDiagram" ],
          [ "GFrameHold", "classmusx_1_1dom_1_1details_1_1GFrameHold.html", "classmusx_1_1dom_1_1details_1_1GFrameHold" ],
          [ "GFrameHoldContext", "classmusx_1_1dom_1_1details_1_1GFrameHoldContext.html", "classmusx_1_1dom_1_1details_1_1GFrameHoldContext" ],
          [ "IndependentStaffDetails", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails.html", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails" ],
          [ "KeySymbolListElement", "classmusx_1_1dom_1_1details_1_1KeySymbolListElement.html", "classmusx_1_1dom_1_1details_1_1KeySymbolListElement" ],
          [ "LyricAssign", "classmusx_1_1dom_1_1details_1_1LyricAssign.html", "classmusx_1_1dom_1_1details_1_1LyricAssign" ],
          [ "LyricAssignChorus", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus.html", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus" ],
          [ "LyricAssignSection", "classmusx_1_1dom_1_1details_1_1LyricAssignSection.html", "classmusx_1_1dom_1_1details_1_1LyricAssignSection" ],
          [ "LyricAssignVerse", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse.html", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse" ],
          [ "LyricEntryInfo", "classmusx_1_1dom_1_1details_1_1LyricEntryInfo.html", "classmusx_1_1dom_1_1details_1_1LyricEntryInfo" ],
          [ "MeasureGraphicAssign", "classmusx_1_1dom_1_1details_1_1MeasureGraphicAssign.html", "classmusx_1_1dom_1_1details_1_1MeasureGraphicAssign" ],
          [ "MeasureNumberIndividualPositioning", "classmusx_1_1dom_1_1details_1_1MeasureNumberIndividualPositioning.html", "classmusx_1_1dom_1_1details_1_1MeasureNumberIndividualPositioning" ],
          [ "MeasureOssiaAssign", "classmusx_1_1dom_1_1details_1_1MeasureOssiaAssign.html", "classmusx_1_1dom_1_1details_1_1MeasureOssiaAssign" ],
          [ "MeasureTextAssign", "classmusx_1_1dom_1_1details_1_1MeasureTextAssign.html", "classmusx_1_1dom_1_1details_1_1MeasureTextAssign" ],
          [ "NoteAlterations", "classmusx_1_1dom_1_1details_1_1NoteAlterations.html", "classmusx_1_1dom_1_1details_1_1NoteAlterations" ],
          [ "PercussionNoteCode", "classmusx_1_1dom_1_1details_1_1PercussionNoteCode.html", "classmusx_1_1dom_1_1details_1_1PercussionNoteCode" ],
          [ "SecondaryBeamAlterationsDownStem", "classmusx_1_1dom_1_1details_1_1SecondaryBeamAlterationsDownStem.html", "classmusx_1_1dom_1_1details_1_1SecondaryBeamAlterationsDownStem" ],
          [ "SecondaryBeamAlterationsUpStem", "classmusx_1_1dom_1_1details_1_1SecondaryBeamAlterationsUpStem.html", "classmusx_1_1dom_1_1details_1_1SecondaryBeamAlterationsUpStem" ],
          [ "SecondaryBeamBreak", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak.html", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak" ],
          [ "ShapeNote", "classmusx_1_1dom_1_1details_1_1ShapeNote.html", "classmusx_1_1dom_1_1details_1_1ShapeNote" ],
          [ "ShapeNoteBase", "classmusx_1_1dom_1_1details_1_1ShapeNoteBase.html", "classmusx_1_1dom_1_1details_1_1ShapeNoteBase" ],
          [ "ShapeNoteStyle", "classmusx_1_1dom_1_1details_1_1ShapeNoteStyle.html", "classmusx_1_1dom_1_1details_1_1ShapeNoteStyle" ],
          [ "SmartShapeEntryAssign", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign.html", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign" ],
          [ "StaffGroup", "classmusx_1_1dom_1_1details_1_1StaffGroup.html", "classmusx_1_1dom_1_1details_1_1StaffGroup" ],
          [ "StaffGroupInfo", "classmusx_1_1dom_1_1details_1_1StaffGroupInfo.html", "classmusx_1_1dom_1_1details_1_1StaffGroupInfo" ],
          [ "StaffSize", "classmusx_1_1dom_1_1details_1_1StaffSize.html", "classmusx_1_1dom_1_1details_1_1StaffSize" ],
          [ "StemAlterations", "classmusx_1_1dom_1_1details_1_1StemAlterations.html", "classmusx_1_1dom_1_1details_1_1StemAlterations" ],
          [ "StemAlterationsUnderBeam", "classmusx_1_1dom_1_1details_1_1StemAlterationsUnderBeam.html", "classmusx_1_1dom_1_1details_1_1StemAlterationsUnderBeam" ],
          [ "TablatureNoteMods", "classmusx_1_1dom_1_1details_1_1TablatureNoteMods.html", "classmusx_1_1dom_1_1details_1_1TablatureNoteMods" ],
          [ "TieAlterBase", "classmusx_1_1dom_1_1details_1_1TieAlterBase.html", "classmusx_1_1dom_1_1details_1_1TieAlterBase" ],
          [ "TieAlterEnd", "classmusx_1_1dom_1_1details_1_1TieAlterEnd.html", "classmusx_1_1dom_1_1details_1_1TieAlterEnd" ],
          [ "TieAlterStart", "classmusx_1_1dom_1_1details_1_1TieAlterStart.html", "classmusx_1_1dom_1_1details_1_1TieAlterStart" ],
          [ "TupletDef", "classmusx_1_1dom_1_1details_1_1TupletDef.html", "classmusx_1_1dom_1_1details_1_1TupletDef" ]
        ] ],
        [ "header", "namespacemusx_1_1dom_1_1header.html", [
          [ "FileInfo", "structmusx_1_1dom_1_1header_1_1FileInfo.html", "structmusx_1_1dom_1_1header_1_1FileInfo" ],
          [ "FinaleVersion", "structmusx_1_1dom_1_1header_1_1FinaleVersion.html", "structmusx_1_1dom_1_1header_1_1FinaleVersion" ],
          [ "Header", "structmusx_1_1dom_1_1header_1_1Header.html", "structmusx_1_1dom_1_1header_1_1Header" ]
        ] ],
        [ "options", "namespacemusx_1_1dom_1_1options.html", [
          [ "AccidentalOptions", "classmusx_1_1dom_1_1options_1_1AccidentalOptions.html", "classmusx_1_1dom_1_1options_1_1AccidentalOptions" ],
          [ "AlternateNotationOptions", "classmusx_1_1dom_1_1options_1_1AlternateNotationOptions.html", "classmusx_1_1dom_1_1options_1_1AlternateNotationOptions" ],
          [ "AugmentationDotOptions", "classmusx_1_1dom_1_1options_1_1AugmentationDotOptions.html", "classmusx_1_1dom_1_1options_1_1AugmentationDotOptions" ],
          [ "BarlineOptions", "classmusx_1_1dom_1_1options_1_1BarlineOptions.html", "classmusx_1_1dom_1_1options_1_1BarlineOptions" ],
          [ "BeamOptions", "classmusx_1_1dom_1_1options_1_1BeamOptions.html", "classmusx_1_1dom_1_1options_1_1BeamOptions" ],
          [ "ChordOptions", "classmusx_1_1dom_1_1options_1_1ChordOptions.html", "classmusx_1_1dom_1_1options_1_1ChordOptions" ],
          [ "ClefOptions", "classmusx_1_1dom_1_1options_1_1ClefOptions.html", "classmusx_1_1dom_1_1options_1_1ClefOptions" ],
          [ "FlagOptions", "classmusx_1_1dom_1_1options_1_1FlagOptions.html", "classmusx_1_1dom_1_1options_1_1FlagOptions" ],
          [ "FontOptions", "classmusx_1_1dom_1_1options_1_1FontOptions.html", "classmusx_1_1dom_1_1options_1_1FontOptions" ],
          [ "GraceNoteOptions", "classmusx_1_1dom_1_1options_1_1GraceNoteOptions.html", "classmusx_1_1dom_1_1options_1_1GraceNoteOptions" ],
          [ "KeySignatureOptions", "classmusx_1_1dom_1_1options_1_1KeySignatureOptions.html", "classmusx_1_1dom_1_1options_1_1KeySignatureOptions" ],
          [ "LineCurveOptions", "classmusx_1_1dom_1_1options_1_1LineCurveOptions.html", "classmusx_1_1dom_1_1options_1_1LineCurveOptions" ],
          [ "LyricOptions", "classmusx_1_1dom_1_1options_1_1LyricOptions.html", "classmusx_1_1dom_1_1options_1_1LyricOptions" ],
          [ "MiscOptions", "classmusx_1_1dom_1_1options_1_1MiscOptions.html", "classmusx_1_1dom_1_1options_1_1MiscOptions" ],
          [ "MultimeasureRestOptions", "classmusx_1_1dom_1_1options_1_1MultimeasureRestOptions.html", "classmusx_1_1dom_1_1options_1_1MultimeasureRestOptions" ],
          [ "MusicSpacingOptions", "classmusx_1_1dom_1_1options_1_1MusicSpacingOptions.html", "classmusx_1_1dom_1_1options_1_1MusicSpacingOptions" ],
          [ "MusicSymbolOptions", "classmusx_1_1dom_1_1options_1_1MusicSymbolOptions.html", "classmusx_1_1dom_1_1options_1_1MusicSymbolOptions" ],
          [ "NoteRestOptions", "classmusx_1_1dom_1_1options_1_1NoteRestOptions.html", "classmusx_1_1dom_1_1options_1_1NoteRestOptions" ],
          [ "PageFormatOptions", "classmusx_1_1dom_1_1options_1_1PageFormatOptions.html", "classmusx_1_1dom_1_1options_1_1PageFormatOptions" ],
          [ "PianoBraceBracketOptions", "classmusx_1_1dom_1_1options_1_1PianoBraceBracketOptions.html", "classmusx_1_1dom_1_1options_1_1PianoBraceBracketOptions" ],
          [ "RepeatOptions", "classmusx_1_1dom_1_1options_1_1RepeatOptions.html", "classmusx_1_1dom_1_1options_1_1RepeatOptions" ],
          [ "SmartShapeOptions", "classmusx_1_1dom_1_1options_1_1SmartShapeOptions.html", "classmusx_1_1dom_1_1options_1_1SmartShapeOptions" ],
          [ "StaffOptions", "classmusx_1_1dom_1_1options_1_1StaffOptions.html", "classmusx_1_1dom_1_1options_1_1StaffOptions" ],
          [ "StemOptions", "classmusx_1_1dom_1_1options_1_1StemOptions.html", "classmusx_1_1dom_1_1options_1_1StemOptions" ],
          [ "TextOptions", "classmusx_1_1dom_1_1options_1_1TextOptions.html", "classmusx_1_1dom_1_1options_1_1TextOptions" ],
          [ "TieOptions", "classmusx_1_1dom_1_1options_1_1TieOptions.html", "classmusx_1_1dom_1_1options_1_1TieOptions" ],
          [ "TimeSignatureOptions", "classmusx_1_1dom_1_1options_1_1TimeSignatureOptions.html", "classmusx_1_1dom_1_1options_1_1TimeSignatureOptions" ],
          [ "TupletOptions", "classmusx_1_1dom_1_1options_1_1TupletOptions.html", "classmusx_1_1dom_1_1options_1_1TupletOptions" ]
        ] ],
        [ "others", "namespacemusx_1_1dom_1_1others.html", [
          [ "AcciAmountFlats", "classmusx_1_1dom_1_1others_1_1AcciAmountFlats.html", "classmusx_1_1dom_1_1others_1_1AcciAmountFlats" ],
          [ "AcciAmountSharps", "classmusx_1_1dom_1_1others_1_1AcciAmountSharps.html", "classmusx_1_1dom_1_1others_1_1AcciAmountSharps" ],
          [ "AcciOrderFlats", "classmusx_1_1dom_1_1others_1_1AcciOrderFlats.html", "classmusx_1_1dom_1_1others_1_1AcciOrderFlats" ],
          [ "AcciOrderSharps", "classmusx_1_1dom_1_1others_1_1AcciOrderSharps.html", "classmusx_1_1dom_1_1others_1_1AcciOrderSharps" ],
          [ "ArticulationDef", "classmusx_1_1dom_1_1others_1_1ArticulationDef.html", "classmusx_1_1dom_1_1others_1_1ArticulationDef" ],
          [ "BeatChartElement", "classmusx_1_1dom_1_1others_1_1BeatChartElement.html", "classmusx_1_1dom_1_1others_1_1BeatChartElement" ],
          [ "ChordSuffixElement", "classmusx_1_1dom_1_1others_1_1ChordSuffixElement.html", "classmusx_1_1dom_1_1others_1_1ChordSuffixElement" ],
          [ "ChordSuffixPlayback", "classmusx_1_1dom_1_1others_1_1ChordSuffixPlayback.html", "classmusx_1_1dom_1_1others_1_1ChordSuffixPlayback" ],
          [ "ClefList", "classmusx_1_1dom_1_1others_1_1ClefList.html", "classmusx_1_1dom_1_1others_1_1ClefList" ],
          [ "DrumStaff", "classmusx_1_1dom_1_1others_1_1DrumStaff.html", "classmusx_1_1dom_1_1others_1_1DrumStaff" ],
          [ "DrumStaffStyle", "classmusx_1_1dom_1_1others_1_1DrumStaffStyle.html", "classmusx_1_1dom_1_1others_1_1DrumStaffStyle" ],
          [ "Enclosure", "classmusx_1_1dom_1_1others_1_1Enclosure.html", "classmusx_1_1dom_1_1others_1_1Enclosure" ],
          [ "EnigmaMusicRange", "classmusx_1_1dom_1_1others_1_1EnigmaMusicRange.html", "classmusx_1_1dom_1_1others_1_1EnigmaMusicRange" ],
          [ "FileAlias", "classmusx_1_1dom_1_1others_1_1FileAlias.html", "classmusx_1_1dom_1_1others_1_1FileAlias" ],
          [ "FileDescription", "classmusx_1_1dom_1_1others_1_1FileDescription.html", "classmusx_1_1dom_1_1others_1_1FileDescription" ],
          [ "FilePath", "classmusx_1_1dom_1_1others_1_1FilePath.html", "classmusx_1_1dom_1_1others_1_1FilePath" ],
          [ "FileUrlBookmark", "classmusx_1_1dom_1_1others_1_1FileUrlBookmark.html", "classmusx_1_1dom_1_1others_1_1FileUrlBookmark" ],
          [ "FontDefinition", "classmusx_1_1dom_1_1others_1_1FontDefinition.html", "classmusx_1_1dom_1_1others_1_1FontDefinition" ],
          [ "Frame", "classmusx_1_1dom_1_1others_1_1Frame.html", "classmusx_1_1dom_1_1others_1_1Frame" ],
          [ "FretboardGroup", "classmusx_1_1dom_1_1others_1_1FretboardGroup.html", "classmusx_1_1dom_1_1others_1_1FretboardGroup" ],
          [ "FretboardStyle", "classmusx_1_1dom_1_1others_1_1FretboardStyle.html", "classmusx_1_1dom_1_1others_1_1FretboardStyle" ],
          [ "FretInstrument", "classmusx_1_1dom_1_1others_1_1FretInstrument.html", "classmusx_1_1dom_1_1others_1_1FretInstrument" ],
          [ "KeyAttributes", "classmusx_1_1dom_1_1others_1_1KeyAttributes.html", "classmusx_1_1dom_1_1others_1_1KeyAttributes" ],
          [ "KeyFormat", "classmusx_1_1dom_1_1others_1_1KeyFormat.html", "classmusx_1_1dom_1_1others_1_1KeyFormat" ],
          [ "KeyMapArray", "classmusx_1_1dom_1_1others_1_1KeyMapArray.html", "classmusx_1_1dom_1_1others_1_1KeyMapArray" ],
          [ "LayerAttributes", "classmusx_1_1dom_1_1others_1_1LayerAttributes.html", "classmusx_1_1dom_1_1others_1_1LayerAttributes" ],
          [ "MarkingCategory", "classmusx_1_1dom_1_1others_1_1MarkingCategory.html", "classmusx_1_1dom_1_1others_1_1MarkingCategory" ],
          [ "MarkingCategoryName", "classmusx_1_1dom_1_1others_1_1MarkingCategoryName.html", "classmusx_1_1dom_1_1others_1_1MarkingCategoryName" ],
          [ "Measure", "classmusx_1_1dom_1_1others_1_1Measure.html", "classmusx_1_1dom_1_1others_1_1Measure" ],
          [ "MeasureExprAssign", "classmusx_1_1dom_1_1others_1_1MeasureExprAssign.html", "classmusx_1_1dom_1_1others_1_1MeasureExprAssign" ],
          [ "MeasureNumberRegion", "classmusx_1_1dom_1_1others_1_1MeasureNumberRegion.html", "classmusx_1_1dom_1_1others_1_1MeasureNumberRegion" ],
          [ "MultimeasureRest", "classmusx_1_1dom_1_1others_1_1MultimeasureRest.html", "classmusx_1_1dom_1_1others_1_1MultimeasureRest" ],
          [ "MultiStaffGroupId", "classmusx_1_1dom_1_1others_1_1MultiStaffGroupId.html", "classmusx_1_1dom_1_1others_1_1MultiStaffGroupId" ],
          [ "MultiStaffInstrumentGroup", "classmusx_1_1dom_1_1others_1_1MultiStaffInstrumentGroup.html", "classmusx_1_1dom_1_1others_1_1MultiStaffInstrumentGroup" ],
          [ "NamePositionAbbreviated", "classmusx_1_1dom_1_1others_1_1NamePositionAbbreviated.html", "classmusx_1_1dom_1_1others_1_1NamePositionAbbreviated" ],
          [ "NamePositionFull", "classmusx_1_1dom_1_1others_1_1NamePositionFull.html", "classmusx_1_1dom_1_1others_1_1NamePositionFull" ],
          [ "NamePositioning", "classmusx_1_1dom_1_1others_1_1NamePositioning.html", "classmusx_1_1dom_1_1others_1_1NamePositioning" ],
          [ "NamePositionStyleAbbreviated", "classmusx_1_1dom_1_1others_1_1NamePositionStyleAbbreviated.html", "classmusx_1_1dom_1_1others_1_1NamePositionStyleAbbreviated" ],
          [ "NamePositionStyleFull", "classmusx_1_1dom_1_1others_1_1NamePositionStyleFull.html", "classmusx_1_1dom_1_1others_1_1NamePositionStyleFull" ],
          [ "OssiaBounds", "classmusx_1_1dom_1_1others_1_1OssiaBounds.html", "classmusx_1_1dom_1_1others_1_1OssiaBounds" ],
          [ "OssiaHeader", "classmusx_1_1dom_1_1others_1_1OssiaHeader.html", "classmusx_1_1dom_1_1others_1_1OssiaHeader" ],
          [ "OssiaMusic", "classmusx_1_1dom_1_1others_1_1OssiaMusic.html", "classmusx_1_1dom_1_1others_1_1OssiaMusic" ],
          [ "Page", "classmusx_1_1dom_1_1others_1_1Page.html", "classmusx_1_1dom_1_1others_1_1Page" ],
          [ "PageGraphicAssign", "classmusx_1_1dom_1_1others_1_1PageGraphicAssign.html", "classmusx_1_1dom_1_1others_1_1PageGraphicAssign" ],
          [ "PageOssiaAssign", "classmusx_1_1dom_1_1others_1_1PageOssiaAssign.html", "classmusx_1_1dom_1_1others_1_1PageOssiaAssign" ],
          [ "PageTextAssign", "classmusx_1_1dom_1_1others_1_1PageTextAssign.html", "classmusx_1_1dom_1_1others_1_1PageTextAssign" ],
          [ "PartDefinition", "classmusx_1_1dom_1_1others_1_1PartDefinition.html", "classmusx_1_1dom_1_1others_1_1PartDefinition" ],
          [ "PartGlobals", "classmusx_1_1dom_1_1others_1_1PartGlobals.html", "classmusx_1_1dom_1_1others_1_1PartGlobals" ],
          [ "PartVoicing", "classmusx_1_1dom_1_1others_1_1PartVoicing.html", "classmusx_1_1dom_1_1others_1_1PartVoicing" ],
          [ "PercussionNoteInfo", "classmusx_1_1dom_1_1others_1_1PercussionNoteInfo.html", "classmusx_1_1dom_1_1others_1_1PercussionNoteInfo" ],
          [ "RepeatBack", "classmusx_1_1dom_1_1others_1_1RepeatBack.html", "classmusx_1_1dom_1_1others_1_1RepeatBack" ],
          [ "RepeatBackIndividualPositioning", "classmusx_1_1dom_1_1others_1_1RepeatBackIndividualPositioning.html", "classmusx_1_1dom_1_1others_1_1RepeatBackIndividualPositioning" ],
          [ "RepeatEndingStart", "classmusx_1_1dom_1_1others_1_1RepeatEndingStart.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingStart" ],
          [ "RepeatEndingStartIndividualPositioning", "classmusx_1_1dom_1_1others_1_1RepeatEndingStartIndividualPositioning.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingStartIndividualPositioning" ],
          [ "RepeatEndingText", "classmusx_1_1dom_1_1others_1_1RepeatEndingText.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingText" ],
          [ "RepeatEndingTextIndividualPositioning", "classmusx_1_1dom_1_1others_1_1RepeatEndingTextIndividualPositioning.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingTextIndividualPositioning" ],
          [ "RepeatIndividualPositioning", "classmusx_1_1dom_1_1others_1_1RepeatIndividualPositioning.html", "classmusx_1_1dom_1_1others_1_1RepeatIndividualPositioning" ],
          [ "RepeatPassList", "classmusx_1_1dom_1_1others_1_1RepeatPassList.html", "classmusx_1_1dom_1_1others_1_1RepeatPassList" ],
          [ "ShapeExpressionDef", "classmusx_1_1dom_1_1others_1_1ShapeExpressionDef.html", "classmusx_1_1dom_1_1others_1_1ShapeExpressionDef" ],
          [ "ShapeGraphicAssign", "classmusx_1_1dom_1_1others_1_1ShapeGraphicAssign.html", "classmusx_1_1dom_1_1others_1_1ShapeGraphicAssign" ],
          [ "SmartShape", "classmusx_1_1dom_1_1others_1_1SmartShape.html", "classmusx_1_1dom_1_1others_1_1SmartShape" ],
          [ "SmartShapeCustomLine", "classmusx_1_1dom_1_1others_1_1SmartShapeCustomLine.html", "classmusx_1_1dom_1_1others_1_1SmartShapeCustomLine" ],
          [ "SmartShapeMeasureAssign", "classmusx_1_1dom_1_1others_1_1SmartShapeMeasureAssign.html", "classmusx_1_1dom_1_1others_1_1SmartShapeMeasureAssign" ],
          [ "SplitMeasure", "classmusx_1_1dom_1_1others_1_1SplitMeasure.html", "classmusx_1_1dom_1_1others_1_1SplitMeasure" ],
          [ "Staff", "classmusx_1_1dom_1_1others_1_1Staff.html", "classmusx_1_1dom_1_1others_1_1Staff" ],
          [ "StaffComposite", "classmusx_1_1dom_1_1others_1_1StaffComposite.html", "classmusx_1_1dom_1_1others_1_1StaffComposite" ],
          [ "StaffList", "classmusx_1_1dom_1_1others_1_1StaffList.html", "classmusx_1_1dom_1_1others_1_1StaffList" ],
          [ "StaffListCategoryName", "classmusx_1_1dom_1_1others_1_1StaffListCategoryName.html", "classmusx_1_1dom_1_1others_1_1StaffListCategoryName" ],
          [ "StaffListCategoryParts", "classmusx_1_1dom_1_1others_1_1StaffListCategoryParts.html", null ],
          [ "StaffListCategoryScore", "classmusx_1_1dom_1_1others_1_1StaffListCategoryScore.html", null ],
          [ "StaffListRepeatName", "classmusx_1_1dom_1_1others_1_1StaffListRepeatName.html", "classmusx_1_1dom_1_1others_1_1StaffListRepeatName" ],
          [ "StaffListRepeatParts", "classmusx_1_1dom_1_1others_1_1StaffListRepeatParts.html", null ],
          [ "StaffListRepeatPartsForced", "classmusx_1_1dom_1_1others_1_1StaffListRepeatPartsForced.html", null ],
          [ "StaffListRepeatScore", "classmusx_1_1dom_1_1others_1_1StaffListRepeatScore.html", null ],
          [ "StaffListRepeatScoreForced", "classmusx_1_1dom_1_1others_1_1StaffListRepeatScoreForced.html", null ],
          [ "StaffListSet", "classmusx_1_1dom_1_1others_1_1StaffListSet.html", "classmusx_1_1dom_1_1others_1_1StaffListSet" ],
          [ "StaffStyle", "classmusx_1_1dom_1_1others_1_1StaffStyle.html", "classmusx_1_1dom_1_1others_1_1StaffStyle" ],
          [ "StaffStyleAssign", "classmusx_1_1dom_1_1others_1_1StaffStyleAssign.html", "classmusx_1_1dom_1_1others_1_1StaffStyleAssign" ],
          [ "StaffSystem", "classmusx_1_1dom_1_1others_1_1StaffSystem.html", "classmusx_1_1dom_1_1others_1_1StaffSystem" ],
          [ "StaffUsed", "classmusx_1_1dom_1_1others_1_1StaffUsed.html", "classmusx_1_1dom_1_1others_1_1StaffUsed" ],
          [ "SystemLock", "classmusx_1_1dom_1_1others_1_1SystemLock.html", "classmusx_1_1dom_1_1others_1_1SystemLock" ],
          [ "TempoChange", "classmusx_1_1dom_1_1others_1_1TempoChange.html", "classmusx_1_1dom_1_1others_1_1TempoChange" ],
          [ "TextBlock", "classmusx_1_1dom_1_1others_1_1TextBlock.html", "classmusx_1_1dom_1_1others_1_1TextBlock" ],
          [ "TextExpressionDef", "classmusx_1_1dom_1_1others_1_1TextExpressionDef.html", "classmusx_1_1dom_1_1others_1_1TextExpressionDef" ],
          [ "TextExpressionEnclosure", "classmusx_1_1dom_1_1others_1_1TextExpressionEnclosure.html", "classmusx_1_1dom_1_1others_1_1TextExpressionEnclosure" ],
          [ "TextRepeatAssign", "classmusx_1_1dom_1_1others_1_1TextRepeatAssign.html", "classmusx_1_1dom_1_1others_1_1TextRepeatAssign" ],
          [ "TextRepeatDef", "classmusx_1_1dom_1_1others_1_1TextRepeatDef.html", "classmusx_1_1dom_1_1others_1_1TextRepeatDef" ],
          [ "TextRepeatEnclosure", "classmusx_1_1dom_1_1others_1_1TextRepeatEnclosure.html", "classmusx_1_1dom_1_1others_1_1TextRepeatEnclosure" ],
          [ "TextRepeatIndividualPositioning", "classmusx_1_1dom_1_1others_1_1TextRepeatIndividualPositioning.html", "classmusx_1_1dom_1_1others_1_1TextRepeatIndividualPositioning" ],
          [ "TextRepeatText", "classmusx_1_1dom_1_1others_1_1TextRepeatText.html", "classmusx_1_1dom_1_1others_1_1TextRepeatText" ],
          [ "TimeCompositeLower", "classmusx_1_1dom_1_1others_1_1TimeCompositeLower.html", "classmusx_1_1dom_1_1others_1_1TimeCompositeLower" ],
          [ "TimeCompositeUpper", "classmusx_1_1dom_1_1others_1_1TimeCompositeUpper.html", "classmusx_1_1dom_1_1others_1_1TimeCompositeUpper" ],
          [ "TonalCenterFlats", "classmusx_1_1dom_1_1others_1_1TonalCenterFlats.html", "classmusx_1_1dom_1_1others_1_1TonalCenterFlats" ],
          [ "TonalCenterSharps", "classmusx_1_1dom_1_1others_1_1TonalCenterSharps.html", "classmusx_1_1dom_1_1others_1_1TonalCenterSharps" ]
        ] ],
        [ "percussion", null, [
          [ "PercussionNoteType", "structmusx_1_1dom_1_1percussion_1_1PercussionNoteType.html", "structmusx_1_1dom_1_1percussion_1_1PercussionNoteType" ]
        ] ],
        [ "smartshape", null, [
          [ "ControlPointAdjustment", "classmusx_1_1dom_1_1smartshape_1_1ControlPointAdjustment.html", "classmusx_1_1dom_1_1smartshape_1_1ControlPointAdjustment" ],
          [ "EndPoint", "classmusx_1_1dom_1_1smartshape_1_1EndPoint.html", "classmusx_1_1dom_1_1smartshape_1_1EndPoint" ],
          [ "EndPointAdjustment", "classmusx_1_1dom_1_1smartshape_1_1EndPointAdjustment.html", "classmusx_1_1dom_1_1smartshape_1_1EndPointAdjustment" ]
        ] ],
        [ "texts", "namespacemusx_1_1dom_1_1texts.html", [
          [ "BlockText", "classmusx_1_1dom_1_1texts_1_1BlockText.html", "classmusx_1_1dom_1_1texts_1_1BlockText" ],
          [ "BookmarkText", "classmusx_1_1dom_1_1texts_1_1BookmarkText.html", "classmusx_1_1dom_1_1texts_1_1BookmarkText" ],
          [ "ExpressionText", "classmusx_1_1dom_1_1texts_1_1ExpressionText.html", "classmusx_1_1dom_1_1texts_1_1ExpressionText" ],
          [ "FileInfoText", "classmusx_1_1dom_1_1texts_1_1FileInfoText.html", "classmusx_1_1dom_1_1texts_1_1FileInfoText" ],
          [ "LyricsChorus", "classmusx_1_1dom_1_1texts_1_1LyricsChorus.html", null ],
          [ "LyricsSection", "classmusx_1_1dom_1_1texts_1_1LyricsSection.html", null ],
          [ "LyricsTextBase", "classmusx_1_1dom_1_1texts_1_1LyricsTextBase.html", "classmusx_1_1dom_1_1texts_1_1LyricsTextBase" ],
          [ "LyricsVerse", "classmusx_1_1dom_1_1texts_1_1LyricsVerse.html", null ],
          [ "SmartShapeText", "classmusx_1_1dom_1_1texts_1_1SmartShapeText.html", "classmusx_1_1dom_1_1texts_1_1SmartShapeText" ]
        ] ],
        [ "Base", "classmusx_1_1dom_1_1Base.html", "classmusx_1_1dom_1_1Base" ],
        [ "CommonClassBase", "classmusx_1_1dom_1_1CommonClassBase.html", "classmusx_1_1dom_1_1CommonClassBase" ],
        [ "ContainedClassBase", "classmusx_1_1dom_1_1ContainedClassBase.html", "classmusx_1_1dom_1_1ContainedClassBase" ],
        [ "DeferredReference", "classmusx_1_1dom_1_1DeferredReference.html", "classmusx_1_1dom_1_1DeferredReference" ],
        [ "DetailsArray", "classmusx_1_1dom_1_1DetailsArray.html", "classmusx_1_1dom_1_1DetailsArray" ],
        [ "DetailsBase", "classmusx_1_1dom_1_1DetailsBase.html", "classmusx_1_1dom_1_1DetailsBase" ],
        [ "DetailsPool", "classmusx_1_1dom_1_1DetailsPool.html", "classmusx_1_1dom_1_1DetailsPool" ],
        [ "Document", "classmusx_1_1dom_1_1Document.html", "classmusx_1_1dom_1_1Document" ],
        [ "EmbeddedGraphicData", "structmusx_1_1dom_1_1EmbeddedGraphicData.html", "structmusx_1_1dom_1_1EmbeddedGraphicData" ],
        [ "Entry", "classmusx_1_1dom_1_1Entry.html", "classmusx_1_1dom_1_1Entry" ],
        [ "EntryDetailsBase", "classmusx_1_1dom_1_1EntryDetailsBase.html", "classmusx_1_1dom_1_1EntryDetailsBase" ],
        [ "EntryFrame", "classmusx_1_1dom_1_1EntryFrame.html", "classmusx_1_1dom_1_1EntryFrame" ],
        [ "EntryInfo", "classmusx_1_1dom_1_1EntryInfo.html", "classmusx_1_1dom_1_1EntryInfo" ],
        [ "EntryInfoPtr", "classmusx_1_1dom_1_1EntryInfoPtr.html", "classmusx_1_1dom_1_1EntryInfoPtr" ],
        [ "EntryPool", "classmusx_1_1dom_1_1EntryPool.html", "classmusx_1_1dom_1_1EntryPool" ],
        [ "FontInfo", "classmusx_1_1dom_1_1FontInfo.html", "classmusx_1_1dom_1_1FontInfo" ],
        [ "InstrumentInfo", "structmusx_1_1dom_1_1InstrumentInfo.html", "structmusx_1_1dom_1_1InstrumentInfo" ],
        [ "integrity_error", "classmusx_1_1dom_1_1integrity__error.html", null ],
        [ "is_pool_type", "structmusx_1_1dom_1_1is__pool__type.html", null ],
        [ "is_pool_type< DetailsPool, T >", "structmusx_1_1dom_1_1is__pool__type_3_01DetailsPool_00_01T_01_4.html", null ],
        [ "is_pool_type< EntryPool, T >", "structmusx_1_1dom_1_1is__pool__type_3_01EntryPool_00_01T_01_4.html", null ],
        [ "is_pool_type< OptionsPool, T >", "structmusx_1_1dom_1_1is__pool__type_3_01OptionsPool_00_01T_01_4.html", null ],
        [ "is_pool_type< OthersPool, T >", "structmusx_1_1dom_1_1is__pool__type_3_01OthersPool_00_01T_01_4.html", null ],
        [ "is_pool_type< TextsPool, T >", "structmusx_1_1dom_1_1is__pool__type_3_01TextsPool_00_01T_01_4.html", null ],
        [ "KeySignature", "classmusx_1_1dom_1_1KeySignature.html", "classmusx_1_1dom_1_1KeySignature" ],
        [ "LyricsLineInfo", "classmusx_1_1dom_1_1LyricsLineInfo.html", "classmusx_1_1dom_1_1LyricsLineInfo" ],
        [ "LyricsSyllableInfo", "classmusx_1_1dom_1_1LyricsSyllableInfo.html", "classmusx_1_1dom_1_1LyricsSyllableInfo" ],
        [ "MusicRange", "classmusx_1_1dom_1_1MusicRange.html", "classmusx_1_1dom_1_1MusicRange" ],
        [ "MusxInstanceList", "classmusx_1_1dom_1_1MusxInstanceList.html", null ],
        [ "MusxInstanceList< others::StaffUsed >", "classmusx_1_1dom_1_1MusxInstanceList_3_01others_1_1StaffUsed_01_4.html", "classmusx_1_1dom_1_1MusxInstanceList_3_01others_1_1StaffUsed_01_4" ],
        [ "MusxInstanceListBase", "classmusx_1_1dom_1_1MusxInstanceListBase.html", "classmusx_1_1dom_1_1MusxInstanceListBase" ],
        [ "Note", "classmusx_1_1dom_1_1Note.html", "classmusx_1_1dom_1_1Note" ],
        [ "NoteDetailsBase", "classmusx_1_1dom_1_1NoteDetailsBase.html", "classmusx_1_1dom_1_1NoteDetailsBase" ],
        [ "NoteInfoPtr", "classmusx_1_1dom_1_1NoteInfoPtr.html", "classmusx_1_1dom_1_1NoteInfoPtr" ],
        [ "ObjectPool", "classmusx_1_1dom_1_1ObjectPool.html", "classmusx_1_1dom_1_1ObjectPool" ],
        [ "OptionsBase", "classmusx_1_1dom_1_1OptionsBase.html", "classmusx_1_1dom_1_1OptionsBase" ],
        [ "OptionsPool", "classmusx_1_1dom_1_1OptionsPool.html", "classmusx_1_1dom_1_1OptionsPool" ],
        [ "OthersArray", "classmusx_1_1dom_1_1OthersArray.html", "classmusx_1_1dom_1_1OthersArray" ],
        [ "OthersBase", "classmusx_1_1dom_1_1OthersBase.html", "classmusx_1_1dom_1_1OthersBase" ],
        [ "OthersName", "classmusx_1_1dom_1_1OthersName.html", "classmusx_1_1dom_1_1OthersName" ],
        [ "OthersPool", "classmusx_1_1dom_1_1OthersPool.html", "classmusx_1_1dom_1_1OthersPool" ],
        [ "ShapeDefInstruction", "structmusx_1_1dom_1_1ShapeDefInstruction.html", "structmusx_1_1dom_1_1ShapeDefInstruction" ],
        [ "TextsBase", "classmusx_1_1dom_1_1TextsBase.html", "classmusx_1_1dom_1_1TextsBase" ],
        [ "TextsPool", "classmusx_1_1dom_1_1TextsPool.html", "classmusx_1_1dom_1_1TextsPool" ],
        [ "TimeSignature", "classmusx_1_1dom_1_1TimeSignature.html", "classmusx_1_1dom_1_1TimeSignature" ]
      ] ],
      [ "factory", "namespacemusx_1_1factory.html", [
        [ "DetailsFactory", "classmusx_1_1factory_1_1DetailsFactory.html", null ],
        [ "DocumentFactory", "classmusx_1_1factory_1_1DocumentFactory.html", "classmusx_1_1factory_1_1DocumentFactory" ],
        [ "ElementLinker", "classmusx_1_1factory_1_1ElementLinker.html", "classmusx_1_1factory_1_1ElementLinker" ],
        [ "EntryFactory", "classmusx_1_1factory_1_1EntryFactory.html", null ],
        [ "FactoryBase", "classmusx_1_1factory_1_1FactoryBase.html", null ],
        [ "HeaderFactory", "classmusx_1_1factory_1_1HeaderFactory.html", null ],
        [ "OptionsFactory", "classmusx_1_1factory_1_1OptionsFactory.html", null ],
        [ "OthersFactory", "classmusx_1_1factory_1_1OthersFactory.html", null ],
        [ "PoolFactory", "classmusx_1_1factory_1_1PoolFactory.html", null ],
        [ "TextsFactory", "classmusx_1_1factory_1_1TextsFactory.html", null ],
        [ "TypeRegistry", "classmusx_1_1factory_1_1TypeRegistry.html", "classmusx_1_1factory_1_1TypeRegistry" ],
        [ "unknown_xml_error", "classmusx_1_1factory_1_1unknown__xml__error.html", null ]
      ] ],
      [ "util", null, [
        [ "DateTime", "structmusx_1_1util_1_1DateTime.html", "structmusx_1_1util_1_1DateTime" ],
        [ "EnigmaParsingContext", "classmusx_1_1util_1_1EnigmaParsingContext.html", "classmusx_1_1util_1_1EnigmaParsingContext" ],
        [ "EnigmaString", "classmusx_1_1util_1_1EnigmaString.html", "classmusx_1_1util_1_1EnigmaString" ],
        [ "EnigmaStyles", "structmusx_1_1util_1_1EnigmaStyles.html", "structmusx_1_1util_1_1EnigmaStyles" ],
        [ "Fraction", "classmusx_1_1util_1_1Fraction.html", "classmusx_1_1util_1_1Fraction" ],
        [ "Logger", "classmusx_1_1util_1_1Logger.html", "classmusx_1_1util_1_1Logger" ],
        [ "SvgConvert", "classmusx_1_1util_1_1SvgConvert.html", "classmusx_1_1util_1_1SvgConvert" ],
        [ "TestConfiguration", "classmusx_1_1util_1_1TestConfiguration.html", null ],
        [ "Tie", "classmusx_1_1util_1_1Tie.html", "classmusx_1_1util_1_1Tie" ]
      ] ],
      [ "utils", null, [
        [ "PseudoTieShapeInfo", "structmusx_1_1utils_1_1PseudoTieShapeInfo.html", "structmusx_1_1utils_1_1PseudoTieShapeInfo" ]
      ] ],
      [ "xml", "namespacemusx_1_1xml.html", [
        [ "pugi", "namespacemusx_1_1xml_1_1pugi.html", [
          [ "Attribute", "classmusx_1_1xml_1_1pugi_1_1Attribute.html", "classmusx_1_1xml_1_1pugi_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1pugi_1_1Document.html", "classmusx_1_1xml_1_1pugi_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1pugi_1_1Element.html", "classmusx_1_1xml_1_1pugi_1_1Element" ]
        ] ],
        [ "rapidxml", "namespacemusx_1_1xml_1_1rapidxml.html", [
          [ "Attribute", "classmusx_1_1xml_1_1rapidxml_1_1Attribute.html", "classmusx_1_1xml_1_1rapidxml_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1rapidxml_1_1Document.html", "classmusx_1_1xml_1_1rapidxml_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1rapidxml_1_1Element.html", "classmusx_1_1xml_1_1rapidxml_1_1Element" ]
        ] ],
        [ "tinyxml2", "namespacemusx_1_1xml_1_1tinyxml2.html", [
          [ "Attribute", "classmusx_1_1xml_1_1tinyxml2_1_1Attribute.html", "classmusx_1_1xml_1_1tinyxml2_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1tinyxml2_1_1Document.html", "classmusx_1_1xml_1_1tinyxml2_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1tinyxml2_1_1Element.html", "classmusx_1_1xml_1_1tinyxml2_1_1Element" ]
        ] ],
        [ "IXmlAttribute", "classmusx_1_1xml_1_1IXmlAttribute.html", "classmusx_1_1xml_1_1IXmlAttribute" ],
        [ "IXmlDocument", "classmusx_1_1xml_1_1IXmlDocument.html", "classmusx_1_1xml_1_1IXmlDocument" ],
        [ "IXmlElement", "classmusx_1_1xml_1_1IXmlElement.html", "classmusx_1_1xml_1_1IXmlElement" ],
        [ "load_error", "classmusx_1_1xml_1_1load__error.html", null ]
      ] ]
    ] ]
];