var annotated_dup =
[
    [ "music_theory", "namespacemusic__theory.html", [
      [ "Transposer", "classmusic__theory_1_1Transposer.html", "classmusic__theory_1_1Transposer" ]
    ] ],
    [ "musx", "namespacemusx.html", [
      [ "dom", "namespacemusx_1_1dom.html", [
        [ "details", "namespacemusx_1_1dom_1_1details.html", [
          [ "ArticulationAssign", "classmusx_1_1dom_1_1details_1_1ArticulationAssign.html", "classmusx_1_1dom_1_1details_1_1ArticulationAssign" ],
          [ "Baseline", "classmusx_1_1dom_1_1details_1_1Baseline.html", "classmusx_1_1dom_1_1details_1_1Baseline" ],
          [ "BaselineLyricsChorus", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus" ],
          [ "BaselineLyricsSection", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection" ],
          [ "BaselineLyricsVerse", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse" ],
          [ "BeamStubDirection", "classmusx_1_1dom_1_1details_1_1BeamStubDirection.html", "classmusx_1_1dom_1_1details_1_1BeamStubDirection" ],
          [ "CrossStaff", "classmusx_1_1dom_1_1details_1_1CrossStaff.html", "classmusx_1_1dom_1_1details_1_1CrossStaff" ],
          [ "GFrameHold", "classmusx_1_1dom_1_1details_1_1GFrameHold.html", "classmusx_1_1dom_1_1details_1_1GFrameHold" ],
          [ "IndependentStaffDetails", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails.html", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails" ],
          [ "LyricAssign", "classmusx_1_1dom_1_1details_1_1LyricAssign.html", "classmusx_1_1dom_1_1details_1_1LyricAssign" ],
          [ "LyricAssignChorus", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus.html", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus" ],
          [ "LyricAssignSection", "classmusx_1_1dom_1_1details_1_1LyricAssignSection.html", "classmusx_1_1dom_1_1details_1_1LyricAssignSection" ],
          [ "LyricAssignVerse", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse.html", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse" ],
          [ "SecondaryBeamBreak", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak.html", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak" ],
          [ "SmartShapeEntryAssign", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign.html", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign" ],
          [ "StaffGroup", "classmusx_1_1dom_1_1details_1_1StaffGroup.html", "classmusx_1_1dom_1_1details_1_1StaffGroup" ],
          [ "TieAlterBase", "classmusx_1_1dom_1_1details_1_1TieAlterBase.html", "classmusx_1_1dom_1_1details_1_1TieAlterBase" ],
          [ "TieAlterEnd", "classmusx_1_1dom_1_1details_1_1TieAlterEnd.html", "classmusx_1_1dom_1_1details_1_1TieAlterEnd" ],
          [ "TieAlterStart", "classmusx_1_1dom_1_1details_1_1TieAlterStart.html", "classmusx_1_1dom_1_1details_1_1TieAlterStart" ],
          [ "TupletDef", "classmusx_1_1dom_1_1details_1_1TupletDef.html", "classmusx_1_1dom_1_1details_1_1TupletDef" ]
        ] ],
        [ "header", "namespacemusx_1_1dom_1_1header.html", [
          [ "FileInfo", "structmusx_1_1dom_1_1header_1_1FileInfo.html", "structmusx_1_1dom_1_1header_1_1FileInfo" ],
          [ "FinaleVersion", "structmusx_1_1dom_1_1header_1_1FinaleVersion.html", "structmusx_1_1dom_1_1header_1_1FinaleVersion" ],
          [ "Header", "structmusx_1_1dom_1_1header_1_1Header.html", "structmusx_1_1dom_1_1header_1_1Header" ]
        ] ],
        [ "options", "namespacemusx_1_1dom_1_1options.html", [
          [ "AccidentalOptions", "classmusx_1_1dom_1_1options_1_1AccidentalOptions.html", "classmusx_1_1dom_1_1options_1_1AccidentalOptions" ],
          [ "AlternateNotationOptions", "classmusx_1_1dom_1_1options_1_1AlternateNotationOptions.html", "classmusx_1_1dom_1_1options_1_1AlternateNotationOptions" ],
          [ "AugmentationDotOptions", "classmusx_1_1dom_1_1options_1_1AugmentationDotOptions.html", "classmusx_1_1dom_1_1options_1_1AugmentationDotOptions" ],
          [ "BarlineOptions", "classmusx_1_1dom_1_1options_1_1BarlineOptions.html", "classmusx_1_1dom_1_1options_1_1BarlineOptions" ],
          [ "BeamOptions", "classmusx_1_1dom_1_1options_1_1BeamOptions.html", "classmusx_1_1dom_1_1options_1_1BeamOptions" ],
          [ "ClefOptions", "classmusx_1_1dom_1_1options_1_1ClefOptions.html", "classmusx_1_1dom_1_1options_1_1ClefOptions" ],
          [ "FlagOptions", "classmusx_1_1dom_1_1options_1_1FlagOptions.html", "classmusx_1_1dom_1_1options_1_1FlagOptions" ],
          [ "FontOptions", "classmusx_1_1dom_1_1options_1_1FontOptions.html", "classmusx_1_1dom_1_1options_1_1FontOptions" ],
          [ "GraceNoteOptions", "classmusx_1_1dom_1_1options_1_1GraceNoteOptions.html", "classmusx_1_1dom_1_1options_1_1GraceNoteOptions" ],
          [ "KeySignatureOptions", "classmusx_1_1dom_1_1options_1_1KeySignatureOptions.html", "classmusx_1_1dom_1_1options_1_1KeySignatureOptions" ],
          [ "LineCurveOptions", "classmusx_1_1dom_1_1options_1_1LineCurveOptions.html", "classmusx_1_1dom_1_1options_1_1LineCurveOptions" ],
          [ "MiscOptions", "classmusx_1_1dom_1_1options_1_1MiscOptions.html", "classmusx_1_1dom_1_1options_1_1MiscOptions" ],
          [ "MultimeasureRestOptions", "classmusx_1_1dom_1_1options_1_1MultimeasureRestOptions.html", "classmusx_1_1dom_1_1options_1_1MultimeasureRestOptions" ],
          [ "MusicSpacingOptions", "classmusx_1_1dom_1_1options_1_1MusicSpacingOptions.html", "classmusx_1_1dom_1_1options_1_1MusicSpacingOptions" ],
          [ "MusicSymbolOptions", "classmusx_1_1dom_1_1options_1_1MusicSymbolOptions.html", "classmusx_1_1dom_1_1options_1_1MusicSymbolOptions" ],
          [ "PageFormatOptions", "classmusx_1_1dom_1_1options_1_1PageFormatOptions.html", "classmusx_1_1dom_1_1options_1_1PageFormatOptions" ],
          [ "PianoBraceBracketOptions", "classmusx_1_1dom_1_1options_1_1PianoBraceBracketOptions.html", "classmusx_1_1dom_1_1options_1_1PianoBraceBracketOptions" ],
          [ "RepeatOptions", "classmusx_1_1dom_1_1options_1_1RepeatOptions.html", "classmusx_1_1dom_1_1options_1_1RepeatOptions" ],
          [ "SmartShapeOptions", "classmusx_1_1dom_1_1options_1_1SmartShapeOptions.html", "classmusx_1_1dom_1_1options_1_1SmartShapeOptions" ],
          [ "StaffOptions", "classmusx_1_1dom_1_1options_1_1StaffOptions.html", "classmusx_1_1dom_1_1options_1_1StaffOptions" ],
          [ "StemOptions", "classmusx_1_1dom_1_1options_1_1StemOptions.html", "classmusx_1_1dom_1_1options_1_1StemOptions" ],
          [ "TieOptions", "classmusx_1_1dom_1_1options_1_1TieOptions.html", "classmusx_1_1dom_1_1options_1_1TieOptions" ],
          [ "TimeSignatureOptions", "classmusx_1_1dom_1_1options_1_1TimeSignatureOptions.html", "classmusx_1_1dom_1_1options_1_1TimeSignatureOptions" ],
          [ "TupletOptions", "classmusx_1_1dom_1_1options_1_1TupletOptions.html", "classmusx_1_1dom_1_1options_1_1TupletOptions" ]
        ] ],
        [ "others", "namespacemusx_1_1dom_1_1others.html", [
          [ "AcciAmountFlats", "classmusx_1_1dom_1_1others_1_1AcciAmountFlats.html", "classmusx_1_1dom_1_1others_1_1AcciAmountFlats" ],
          [ "AcciAmountSharps", "classmusx_1_1dom_1_1others_1_1AcciAmountSharps.html", "classmusx_1_1dom_1_1others_1_1AcciAmountSharps" ],
          [ "AcciOrderFlats", "classmusx_1_1dom_1_1others_1_1AcciOrderFlats.html", "classmusx_1_1dom_1_1others_1_1AcciOrderFlats" ],
          [ "AcciOrderSharps", "classmusx_1_1dom_1_1others_1_1AcciOrderSharps.html", "classmusx_1_1dom_1_1others_1_1AcciOrderSharps" ],
          [ "ArticulationDef", "classmusx_1_1dom_1_1others_1_1ArticulationDef.html", "classmusx_1_1dom_1_1others_1_1ArticulationDef" ],
          [ "BeatChartElement", "classmusx_1_1dom_1_1others_1_1BeatChartElement.html", "classmusx_1_1dom_1_1others_1_1BeatChartElement" ],
          [ "ClefList", "classmusx_1_1dom_1_1others_1_1ClefList.html", "classmusx_1_1dom_1_1others_1_1ClefList" ],
          [ "Enclosure", "classmusx_1_1dom_1_1others_1_1Enclosure.html", "classmusx_1_1dom_1_1others_1_1Enclosure" ],
          [ "FontDefinition", "classmusx_1_1dom_1_1others_1_1FontDefinition.html", "classmusx_1_1dom_1_1others_1_1FontDefinition" ],
          [ "Frame", "classmusx_1_1dom_1_1others_1_1Frame.html", "classmusx_1_1dom_1_1others_1_1Frame" ],
          [ "InstrumentUsed", "classmusx_1_1dom_1_1others_1_1InstrumentUsed.html", "classmusx_1_1dom_1_1others_1_1InstrumentUsed" ],
          [ "KeyFormat", "classmusx_1_1dom_1_1others_1_1KeyFormat.html", "classmusx_1_1dom_1_1others_1_1KeyFormat" ],
          [ "KeyMapArray", "classmusx_1_1dom_1_1others_1_1KeyMapArray.html", "classmusx_1_1dom_1_1others_1_1KeyMapArray" ],
          [ "LayerAttributes", "classmusx_1_1dom_1_1others_1_1LayerAttributes.html", "classmusx_1_1dom_1_1others_1_1LayerAttributes" ],
          [ "MarkingCategory", "classmusx_1_1dom_1_1others_1_1MarkingCategory.html", "classmusx_1_1dom_1_1others_1_1MarkingCategory" ],
          [ "MarkingCategoryName", "classmusx_1_1dom_1_1others_1_1MarkingCategoryName.html", "classmusx_1_1dom_1_1others_1_1MarkingCategoryName" ],
          [ "Measure", "classmusx_1_1dom_1_1others_1_1Measure.html", "classmusx_1_1dom_1_1others_1_1Measure" ],
          [ "MeasureExprAssign", "classmusx_1_1dom_1_1others_1_1MeasureExprAssign.html", "classmusx_1_1dom_1_1others_1_1MeasureExprAssign" ],
          [ "MeasureNumberRegion", "classmusx_1_1dom_1_1others_1_1MeasureNumberRegion.html", "classmusx_1_1dom_1_1others_1_1MeasureNumberRegion" ],
          [ "MultimeasureRest", "classmusx_1_1dom_1_1others_1_1MultimeasureRest.html", "classmusx_1_1dom_1_1others_1_1MultimeasureRest" ],
          [ "MultiStaffGroupId", "classmusx_1_1dom_1_1others_1_1MultiStaffGroupId.html", "classmusx_1_1dom_1_1others_1_1MultiStaffGroupId" ],
          [ "MultiStaffInstrumentGroup", "classmusx_1_1dom_1_1others_1_1MultiStaffInstrumentGroup.html", "classmusx_1_1dom_1_1others_1_1MultiStaffInstrumentGroup" ],
          [ "MusicRange", "classmusx_1_1dom_1_1others_1_1MusicRange.html", "classmusx_1_1dom_1_1others_1_1MusicRange" ],
          [ "NamePositioning", "classmusx_1_1dom_1_1others_1_1NamePositioning.html", "classmusx_1_1dom_1_1others_1_1NamePositioning" ],
          [ "Page", "classmusx_1_1dom_1_1others_1_1Page.html", "classmusx_1_1dom_1_1others_1_1Page" ],
          [ "PartDefinition", "classmusx_1_1dom_1_1others_1_1PartDefinition.html", "classmusx_1_1dom_1_1others_1_1PartDefinition" ],
          [ "PartGlobals", "classmusx_1_1dom_1_1others_1_1PartGlobals.html", "classmusx_1_1dom_1_1others_1_1PartGlobals" ],
          [ "RepeatBack", "classmusx_1_1dom_1_1others_1_1RepeatBack.html", "classmusx_1_1dom_1_1others_1_1RepeatBack" ],
          [ "RepeatEndingStart", "classmusx_1_1dom_1_1others_1_1RepeatEndingStart.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingStart" ],
          [ "RepeatEndingText", "classmusx_1_1dom_1_1others_1_1RepeatEndingText.html", "classmusx_1_1dom_1_1others_1_1RepeatEndingText" ],
          [ "RepeatPassList", "classmusx_1_1dom_1_1others_1_1RepeatPassList.html", "classmusx_1_1dom_1_1others_1_1RepeatPassList" ],
          [ "ShapeData", "classmusx_1_1dom_1_1others_1_1ShapeData.html", "classmusx_1_1dom_1_1others_1_1ShapeData" ],
          [ "ShapeDef", "classmusx_1_1dom_1_1others_1_1ShapeDef.html", "classmusx_1_1dom_1_1others_1_1ShapeDef" ],
          [ "ShapeExpressionDef", "classmusx_1_1dom_1_1others_1_1ShapeExpressionDef.html", "classmusx_1_1dom_1_1others_1_1ShapeExpressionDef" ],
          [ "ShapeInstructionList", "classmusx_1_1dom_1_1others_1_1ShapeInstructionList.html", "classmusx_1_1dom_1_1others_1_1ShapeInstructionList" ],
          [ "SmartShape", "classmusx_1_1dom_1_1others_1_1SmartShape.html", "classmusx_1_1dom_1_1others_1_1SmartShape" ],
          [ "SmartShapeMeasureAssign", "classmusx_1_1dom_1_1others_1_1SmartShapeMeasureAssign.html", "classmusx_1_1dom_1_1others_1_1SmartShapeMeasureAssign" ],
          [ "Staff", "classmusx_1_1dom_1_1others_1_1Staff.html", "classmusx_1_1dom_1_1others_1_1Staff" ],
          [ "StaffComposite", "classmusx_1_1dom_1_1others_1_1StaffComposite.html", null ],
          [ "StaffStyle", "classmusx_1_1dom_1_1others_1_1StaffStyle.html", "classmusx_1_1dom_1_1others_1_1StaffStyle" ],
          [ "StaffStyleAssign", "classmusx_1_1dom_1_1others_1_1StaffStyleAssign.html", "classmusx_1_1dom_1_1others_1_1StaffStyleAssign" ],
          [ "StaffSystem", "classmusx_1_1dom_1_1others_1_1StaffSystem.html", "classmusx_1_1dom_1_1others_1_1StaffSystem" ],
          [ "TempoChange", "classmusx_1_1dom_1_1others_1_1TempoChange.html", "classmusx_1_1dom_1_1others_1_1TempoChange" ],
          [ "TextBlock", "classmusx_1_1dom_1_1others_1_1TextBlock.html", "classmusx_1_1dom_1_1others_1_1TextBlock" ],
          [ "TextExpressionDef", "classmusx_1_1dom_1_1others_1_1TextExpressionDef.html", "classmusx_1_1dom_1_1others_1_1TextExpressionDef" ],
          [ "TextExpressionEnclosure", "classmusx_1_1dom_1_1others_1_1TextExpressionEnclosure.html", "classmusx_1_1dom_1_1others_1_1TextExpressionEnclosure" ],
          [ "TextRepeatAssign", "classmusx_1_1dom_1_1others_1_1TextRepeatAssign.html", "classmusx_1_1dom_1_1others_1_1TextRepeatAssign" ],
          [ "TextRepeatDef", "classmusx_1_1dom_1_1others_1_1TextRepeatDef.html", "classmusx_1_1dom_1_1others_1_1TextRepeatDef" ],
          [ "TextRepeatEnclosure", "classmusx_1_1dom_1_1others_1_1TextRepeatEnclosure.html", "classmusx_1_1dom_1_1others_1_1TextRepeatEnclosure" ],
          [ "TextRepeatText", "classmusx_1_1dom_1_1others_1_1TextRepeatText.html", "classmusx_1_1dom_1_1others_1_1TextRepeatText" ],
          [ "TimeCompositeLower", "classmusx_1_1dom_1_1others_1_1TimeCompositeLower.html", "classmusx_1_1dom_1_1others_1_1TimeCompositeLower" ],
          [ "TimeCompositeUpper", "classmusx_1_1dom_1_1others_1_1TimeCompositeUpper.html", "classmusx_1_1dom_1_1others_1_1TimeCompositeUpper" ],
          [ "TonalCenterFlats", "classmusx_1_1dom_1_1others_1_1TonalCenterFlats.html", "classmusx_1_1dom_1_1others_1_1TonalCenterFlats" ],
          [ "TonalCenterSharps", "classmusx_1_1dom_1_1others_1_1TonalCenterSharps.html", "classmusx_1_1dom_1_1others_1_1TonalCenterSharps" ]
        ] ],
        [ "texts", "namespacemusx_1_1dom_1_1texts.html", [
          [ "BlockText", "classmusx_1_1dom_1_1texts_1_1BlockText.html", "classmusx_1_1dom_1_1texts_1_1BlockText" ],
          [ "BookmarkText", "classmusx_1_1dom_1_1texts_1_1BookmarkText.html", "classmusx_1_1dom_1_1texts_1_1BookmarkText" ],
          [ "ExpressionText", "classmusx_1_1dom_1_1texts_1_1ExpressionText.html", "classmusx_1_1dom_1_1texts_1_1ExpressionText" ],
          [ "FileInfoText", "classmusx_1_1dom_1_1texts_1_1FileInfoText.html", "classmusx_1_1dom_1_1texts_1_1FileInfoText" ],
          [ "LyricsChorus", "classmusx_1_1dom_1_1texts_1_1LyricsChorus.html", null ],
          [ "LyricsSection", "classmusx_1_1dom_1_1texts_1_1LyricsSection.html", null ],
          [ "LyricsTextBase", "classmusx_1_1dom_1_1texts_1_1LyricsTextBase.html", "classmusx_1_1dom_1_1texts_1_1LyricsTextBase" ],
          [ "LyricsVerse", "classmusx_1_1dom_1_1texts_1_1LyricsVerse.html", null ],
          [ "SmartShapeText", "classmusx_1_1dom_1_1texts_1_1SmartShapeText.html", "classmusx_1_1dom_1_1texts_1_1SmartShapeText" ]
        ] ],
        [ "Base", "classmusx_1_1dom_1_1Base.html", "classmusx_1_1dom_1_1Base" ],
        [ "CommonClassBase", "classmusx_1_1dom_1_1CommonClassBase.html", "classmusx_1_1dom_1_1CommonClassBase" ],
        [ "DetailsBase", "classmusx_1_1dom_1_1DetailsBase.html", "classmusx_1_1dom_1_1DetailsBase" ],
        [ "DetailsPool", "classmusx_1_1dom_1_1DetailsPool.html", "classmusx_1_1dom_1_1DetailsPool" ],
        [ "Document", "classmusx_1_1dom_1_1Document.html", "classmusx_1_1dom_1_1Document" ],
        [ "Entry", "classmusx_1_1dom_1_1Entry.html", "classmusx_1_1dom_1_1Entry" ],
        [ "EntryDetailsBase", "classmusx_1_1dom_1_1EntryDetailsBase.html", "classmusx_1_1dom_1_1EntryDetailsBase" ],
        [ "EntryFrame", "classmusx_1_1dom_1_1EntryFrame.html", "classmusx_1_1dom_1_1EntryFrame" ],
        [ "EntryInfo", "classmusx_1_1dom_1_1EntryInfo.html", "classmusx_1_1dom_1_1EntryInfo" ],
        [ "EntryInfoPtr", "classmusx_1_1dom_1_1EntryInfoPtr.html", "classmusx_1_1dom_1_1EntryInfoPtr" ],
        [ "EntryPool", "classmusx_1_1dom_1_1EntryPool.html", "classmusx_1_1dom_1_1EntryPool" ],
        [ "FontInfo", "classmusx_1_1dom_1_1FontInfo.html", "classmusx_1_1dom_1_1FontInfo" ],
        [ "integrity_error", "classmusx_1_1dom_1_1integrity__error.html", null ],
        [ "KeySignature", "classmusx_1_1dom_1_1KeySignature.html", "classmusx_1_1dom_1_1KeySignature" ],
        [ "LyricsSyllableInfo", "classmusx_1_1dom_1_1LyricsSyllableInfo.html", "classmusx_1_1dom_1_1LyricsSyllableInfo" ],
        [ "Note", "classmusx_1_1dom_1_1Note.html", "classmusx_1_1dom_1_1Note" ],
        [ "NoteDetailsBase", "classmusx_1_1dom_1_1NoteDetailsBase.html", "classmusx_1_1dom_1_1NoteDetailsBase" ],
        [ "NoteInfoPtr", "classmusx_1_1dom_1_1NoteInfoPtr.html", "classmusx_1_1dom_1_1NoteInfoPtr" ],
        [ "ObjectPool", "classmusx_1_1dom_1_1ObjectPool.html", "classmusx_1_1dom_1_1ObjectPool" ],
        [ "OptionsBase", "classmusx_1_1dom_1_1OptionsBase.html", "classmusx_1_1dom_1_1OptionsBase" ],
        [ "OptionsPool", "classmusx_1_1dom_1_1OptionsPool.html", "classmusx_1_1dom_1_1OptionsPool" ],
        [ "OthersArray", "classmusx_1_1dom_1_1OthersArray.html", "classmusx_1_1dom_1_1OthersArray" ],
        [ "OthersBase", "classmusx_1_1dom_1_1OthersBase.html", "classmusx_1_1dom_1_1OthersBase" ],
        [ "OthersPool", "classmusx_1_1dom_1_1OthersPool.html", "classmusx_1_1dom_1_1OthersPool" ],
        [ "TextsBase", "classmusx_1_1dom_1_1TextsBase.html", "classmusx_1_1dom_1_1TextsBase" ],
        [ "TextsPool", "classmusx_1_1dom_1_1TextsPool.html", "classmusx_1_1dom_1_1TextsPool" ],
        [ "TimeSignature", "classmusx_1_1dom_1_1TimeSignature.html", "classmusx_1_1dom_1_1TimeSignature" ]
      ] ],
      [ "factory", "namespacemusx_1_1factory.html", [
        [ "DetailsFactory", "classmusx_1_1factory_1_1DetailsFactory.html", null ],
        [ "DocumentFactory", "classmusx_1_1factory_1_1DocumentFactory.html", null ],
        [ "ElementLinker", "classmusx_1_1factory_1_1ElementLinker.html", "classmusx_1_1factory_1_1ElementLinker" ],
        [ "EntryFactory", "classmusx_1_1factory_1_1EntryFactory.html", null ],
        [ "FactoryBase", "classmusx_1_1factory_1_1FactoryBase.html", null ],
        [ "HeaderFactory", "classmusx_1_1factory_1_1HeaderFactory.html", null ],
        [ "OptionsFactory", "classmusx_1_1factory_1_1OptionsFactory.html", null ],
        [ "OthersFactory", "classmusx_1_1factory_1_1OthersFactory.html", null ],
        [ "PoolFactory", "classmusx_1_1factory_1_1PoolFactory.html", null ],
        [ "TextsFactory", "classmusx_1_1factory_1_1TextsFactory.html", null ],
        [ "TypeRegistry", "classmusx_1_1factory_1_1TypeRegistry.html", null ],
        [ "unknown_xml_error", "classmusx_1_1factory_1_1unknown__xml__error.html", null ]
      ] ],
      [ "util", null, [
        [ "EnigmaString", "classmusx_1_1util_1_1EnigmaString.html", "classmusx_1_1util_1_1EnigmaString" ],
        [ "Fraction", "classmusx_1_1util_1_1Fraction.html", "classmusx_1_1util_1_1Fraction" ],
        [ "Logger", "classmusx_1_1util_1_1Logger.html", "classmusx_1_1util_1_1Logger" ]
      ] ],
      [ "xml", "namespacemusx_1_1xml.html", [
        [ "pugi", "namespacemusx_1_1xml_1_1pugi.html", [
          [ "Attribute", "classmusx_1_1xml_1_1pugi_1_1Attribute.html", "classmusx_1_1xml_1_1pugi_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1pugi_1_1Document.html", "classmusx_1_1xml_1_1pugi_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1pugi_1_1Element.html", "classmusx_1_1xml_1_1pugi_1_1Element" ]
        ] ],
        [ "rapidxml", "namespacemusx_1_1xml_1_1rapidxml.html", [
          [ "Attribute", "classmusx_1_1xml_1_1rapidxml_1_1Attribute.html", "classmusx_1_1xml_1_1rapidxml_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1rapidxml_1_1Document.html", "classmusx_1_1xml_1_1rapidxml_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1rapidxml_1_1Element.html", "classmusx_1_1xml_1_1rapidxml_1_1Element" ]
        ] ],
        [ "tinyxml2", "namespacemusx_1_1xml_1_1tinyxml2.html", [
          [ "Attribute", "classmusx_1_1xml_1_1tinyxml2_1_1Attribute.html", "classmusx_1_1xml_1_1tinyxml2_1_1Attribute" ],
          [ "Document", "classmusx_1_1xml_1_1tinyxml2_1_1Document.html", "classmusx_1_1xml_1_1tinyxml2_1_1Document" ],
          [ "Element", "classmusx_1_1xml_1_1tinyxml2_1_1Element.html", "classmusx_1_1xml_1_1tinyxml2_1_1Element" ]
        ] ],
        [ "IXmlAttribute", "classmusx_1_1xml_1_1IXmlAttribute.html", "classmusx_1_1xml_1_1IXmlAttribute" ],
        [ "IXmlDocument", "classmusx_1_1xml_1_1IXmlDocument.html", "classmusx_1_1xml_1_1IXmlDocument" ],
        [ "IXmlElement", "classmusx_1_1xml_1_1IXmlElement.html", "classmusx_1_1xml_1_1IXmlElement" ],
        [ "load_error", "classmusx_1_1xml_1_1load__error.html", null ]
      ] ]
    ] ]
];