var namespacemusx_1_1dom_1_1details =
[
    [ "ArticulationAssign", "classmusx_1_1dom_1_1details_1_1ArticulationAssign.html", "classmusx_1_1dom_1_1details_1_1ArticulationAssign" ],
    [ "Baseline", "classmusx_1_1dom_1_1details_1_1Baseline.html", "classmusx_1_1dom_1_1details_1_1Baseline" ],
    [ "BaselineLyricsChorus", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsChorus" ],
    [ "BaselineLyricsSection", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsSection" ],
    [ "BaselineLyricsVerse", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse.html", "classmusx_1_1dom_1_1details_1_1BaselineLyricsVerse" ],
    [ "BeamStubDirection", "classmusx_1_1dom_1_1details_1_1BeamStubDirection.html", "classmusx_1_1dom_1_1details_1_1BeamStubDirection" ],
    [ "CenterShape", "classmusx_1_1dom_1_1details_1_1CenterShape.html", "classmusx_1_1dom_1_1details_1_1CenterShape" ],
    [ "ChordAssign", "classmusx_1_1dom_1_1details_1_1ChordAssign.html", "classmusx_1_1dom_1_1details_1_1ChordAssign" ],
    [ "CrossStaff", "classmusx_1_1dom_1_1details_1_1CrossStaff.html", "classmusx_1_1dom_1_1details_1_1CrossStaff" ],
    [ "GFrameHold", "classmusx_1_1dom_1_1details_1_1GFrameHold.html", "classmusx_1_1dom_1_1details_1_1GFrameHold" ],
    [ "IndependentStaffDetails", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails.html", "classmusx_1_1dom_1_1details_1_1IndependentStaffDetails" ],
    [ "LyricAssign", "classmusx_1_1dom_1_1details_1_1LyricAssign.html", "classmusx_1_1dom_1_1details_1_1LyricAssign" ],
    [ "LyricAssignChorus", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus.html", "classmusx_1_1dom_1_1details_1_1LyricAssignChorus" ],
    [ "LyricAssignSection", "classmusx_1_1dom_1_1details_1_1LyricAssignSection.html", "classmusx_1_1dom_1_1details_1_1LyricAssignSection" ],
    [ "LyricAssignVerse", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse.html", "classmusx_1_1dom_1_1details_1_1LyricAssignVerse" ],
    [ "MeasureTextAssign", "classmusx_1_1dom_1_1details_1_1MeasureTextAssign.html", "classmusx_1_1dom_1_1details_1_1MeasureTextAssign" ],
    [ "SecondaryBeamBreak", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak.html", "classmusx_1_1dom_1_1details_1_1SecondaryBeamBreak" ],
    [ "SmartShapeEntryAssign", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign.html", "classmusx_1_1dom_1_1details_1_1SmartShapeEntryAssign" ],
    [ "StaffGroup", "classmusx_1_1dom_1_1details_1_1StaffGroup.html", "classmusx_1_1dom_1_1details_1_1StaffGroup" ],
    [ "StaffGroupInfo", "classmusx_1_1dom_1_1details_1_1StaffGroupInfo.html", "classmusx_1_1dom_1_1details_1_1StaffGroupInfo" ],
    [ "TieAlterBase", "classmusx_1_1dom_1_1details_1_1TieAlterBase.html", "classmusx_1_1dom_1_1details_1_1TieAlterBase" ],
    [ "TieAlterEnd", "classmusx_1_1dom_1_1details_1_1TieAlterEnd.html", "classmusx_1_1dom_1_1details_1_1TieAlterEnd" ],
    [ "TieAlterStart", "classmusx_1_1dom_1_1details_1_1TieAlterStart.html", "classmusx_1_1dom_1_1details_1_1TieAlterStart" ],
    [ "TupletDef", "classmusx_1_1dom_1_1details_1_1TupletDef.html", "classmusx_1_1dom_1_1details_1_1TupletDef" ]
];