/*
 * Copyright (C) 2025, Robert Patterson
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/** @mainpage
 * Welcome to the <b>Musx Document Model</b>.
 *
 * Use the <b>navigation buttons</b> at the top of this page to browse through
 * the framework documentation.
 *
 * The Musx Document Model is a <b>C++ class framework</b>
 * around the EnigmaXml format embedded in `.musx` files generated by Finale music software.
 * It requires the C++17 standard.
 *
 * Features include:
 * - Dependency-free class definitions.
 * - Factory classes separate from object model classes.
 * - Xml Deserializer interfaces that allow the caller to use any Xml utility for xml handling.
 *
 * The following macro definitions are available to modify behavior of the library.
 * - `MUSX_DISPLAY_NODE_NAMES`: Log each node name that is processed in the order found. (When verbose logging is specified.)
 * - `MUSX_THROW_ON_UNKNOWN_XML`: Throws `musx::factory::unknown_xml_error` if an unknown child node is encountered. Otherwise
 * it logs the message, which by default sends it to `std::cerr`. This macro does not affect unknown top-level nodes,
 * which are always silently skipped.
 * - `MUSX_THROW_ON_INTEGRITY_CHECK_FAIL`: Throws `musx::dom::integrity_error` if a class fails its integrity check.
 * Otherwise it it logs the message, which by default sends it to `std::cerr`.
 *
 * The recommended way to define these macros is from your make file or build project. They are primarily intended
 * for debugging.
 *
 * The EnigmaXml that is extracted from a `.musx` file follows the pattern that any missing node receives the default value.
 * This is mainly interesting for booleans and enums. The xml nodes for booleans only show up if they are `true`. The default
 * values for enums do not show up either, which means it is frequently difficult to know what their string values might be. For this
 * reason, default enum values are usually omitted from the `XmlEnumMapping` tables.
 *
 * <b>The Musx Document Model project is not affiliated with or endorsed by Finale or its parent company</b>.
 * - It is an independent open-source library designed to help users access and convert their own data in the absence of Finale, which has been discontinued.
 * - It does not contain any Finale source code.
 * - It is not capable of writing Finale files, only reading them.
 * - It has been separately developed by analyzing the contents of EnigmaXml files and other publically available resources, such as the [PDK Framework](https://pdk.finalelua.com/) for Finale and Jari Williamsson’s [original site](https://www.finaletips.nu/frameworkref/index.html).
 * - Nothing in the repository circumvents digital copy protection on the Finale application.
 *
 * (This reference web-site is generated directly from the source code by the Doxygen application.)
 *
 * @author Robert Patterson
 */

#pragma once

#include "music_theory/music_theory.hpp"

#include "util/Fraction.h"
#include "util/DateTimeFormat.h"
#include "util/EnigmaString.h"
#include "util/PseudoTieUtils.h"
#include "util/ShapeRecognize.h"
#include "util/SvgConvert.h"
#include "util/Logger.h"
#include "util/TestSupport.h"
#include "util/Tie.h"
#include "xml/XmlInterface.h"
#include "dom/Document.h"
#include "factory/DocumentFactory.h"
#include "dom/InstrumentUuids.h"
#include "dom/PercussionNoteType.h"

#ifdef MUSX_USE_TINYXML2 // usually defined on the compile line or in CMakeLists.txt
#include "xml/TinyXmlImpl.h"
#endif

#ifdef MUSX_USE_RAPIDXML // usually defined on the compile line or in CMakeLists.txt
#include "xml/RapidXmlImpl.h"
#endif

#ifdef MUSX_USE_PUGIXML // usually defined on the compile line or in CMakeLists.txt
#include "xml/PugiXmlImpl.h"
#endif

#ifdef MUSX_USE_QTXML // usually defined on the compile line or in CMakeLists.txt
#include "xml/QtXmlImpl.h"
#endif
