// This file is auto-generated from glyphnames.json
#pragma once

#include <unordered_map>
#include <string_view>

namespace musx::fontmaps::glyphnames {

struct GlyphInfo {
    char32_t codepoint;
    std::string_view description;
};

inline const std::unordered_map<std::string_view, GlyphInfo> finaleGlyphnames = {
    { "4stringTabClefSerif", { 0xF40D, "4-string tab clef (serif)" } },
    { "4stringTabClefTall", { 0xF40C, "4-string tab clef (tall)" } },
    { "6stringTabClefSerif", { 0xF40B, "6-string tab clef (serif)" } },
    { "6stringTabClefTall", { 0xF40A, "6-string tab clef (tall)" } },
    { "accdnPushAlt", { 0xF45B, "Push (Draugsvoll & Højsgaard)" } },
    { "accidentalDoubleFlatJoinedStems", { 0xF4A1, "Double flat (joined stems)" } },
    { "accidentalDoubleFlatParens", { 0xF5D9, "Double flat (parentheses)" } },
    { "accidentalDoubleFlatParenthesesSmall", { 0xF719, "Double flat (parentheses small)" } },
    { "accidentalDoubleFlatSmall", { 0xF714, "Double flat (small)" } },
    { "accidentalDoubleSharpParens", { 0xF5D8, "Double sharp (parentheses)" } },
    { "accidentalDoubleSharpParenthesesSmall", { 0xF715, "Double sharp (parentheses small)" } },
    { "accidentalDoubleSharpSmall", { 0xF710, "Double sharp (small)" } },
    { "accidentalFlatJohnstonDown", { 0xF5DF, "Flat-down arrow (Johnston)" } },
    { "accidentalFlatJohnstonEl", { 0xF5DD, "Flat-inverted seven (Johnston)" } },
    { "accidentalFlatJohnstonElDown", { 0xF5EB, "Flat-inverted seven-down arrow (Johnston)" } },
    { "accidentalFlatJohnstonUp", { 0xF5DE, "Flat-up arrow (Johnston)" } },
    { "accidentalFlatJohnstonUpEl", { 0xF5EA, "Flat-up arrow-inverted seven (Johnston)" } },
    { "accidentalFlatParens", { 0xF5D5, "Flat (parentheses)" } },
    { "accidentalFlatParenthesesSmall", { 0xF718, "Flat (parentheses small)" } },
    { "accidentalFlatSmall", { 0xF713, "Flat (for small staves)" } },
    { "accidentalJohnstonDownEl", { 0xF5E5, "Down arrow-inverted seven (Johnston)" } },
    { "accidentalJohnstonSevenDown", { 0xF5E3, "Seven-down arrow (Johnston)" } },
    { "accidentalJohnstonSevenFlat", { 0xF5E1, "Seven-flat (Johnston)" } },
    { "accidentalJohnstonSevenFlatDown", { 0xF5ED, "Seven-flat-down arrow (Johnston)" } },
    { "accidentalJohnstonSevenFlatUp", { 0xF5EC, "Seven-flat-up arrow (Johnston)" } },
    { "accidentalJohnstonSevenSharp", { 0xF5E0, "Seven-sharp (Johnston)" } },
    { "accidentalJohnstonSevenSharpDown", { 0xF5E9, "Seven-sharp-down arrow (Johnston)" } },
    { "accidentalJohnstonSevenSharpUp", { 0xF5E8, "Seven-sharp-up arrow (Johnston)" } },
    { "accidentalJohnstonSevenUp", { 0xF5E2, "Seven-up arrow (Johnston)" } },
    { "accidentalJohnstonUpEl", { 0xF5E4, "Up arrow-inverted seven (Johnston)" } },
    { "accidentalNaturalParens", { 0xF5D6, "Natural (parentheses)" } },
    { "accidentalNaturalParenthesesSmall", { 0xF717, "Natural (parentheses small)" } },
    { "accidentalNaturalSmall", { 0xF712, "Natural (for small staves)" } },
    { "accidentalSharpJohnstonDown", { 0xF5DC, "Sharp-down arrow (Johnston)" } },
    { "accidentalSharpJohnstonDownEl", { 0xF5E7, "Sharp-down arrow-inverted seven (Johnston)" } },
    { "accidentalSharpJohnstonEl", { 0xF5DA, "Sharp-inverted seven (Johnston)" } },
    { "accidentalSharpJohnstonUp", { 0xF5DB, "Sharp-up arrow (Johnston)" } },
    { "accidentalSharpJohnstonUpEl", { 0xF5E6, "Sharp-up arrow-inverted seven (Johnston)" } },
    { "accidentalSharpParens", { 0xF5D7, "Sharp (parentheses)" } },
    { "accidentalSharpParenthesesSmall", { 0xF716, "Sharp (parentheses small)" } },
    { "accidentalSharpSmall", { 0xF711, "Sharp (for small staves)" } },
    { "accidentalTripleFlatJoinedStems", { 0xF4A2, "Triple flat (joined stems)" } },
    { "analyticsArrowExtension", { 0xF7EA, "Analytics short extension" } },
    { "analyticsArrowRightSegment", { 0xF7E9, "Analytics arrow segment (right)" } },
    { "analyticsArrowRightSegmentTall", { 0xF7EC, "Analytics tall arrow segment (right)" } },
    { "analyticsArrowSegmentRight", { 0xF7ED, "Analytics arrow (right)" } },
    { "analyticsArrowShort", { 0xF7EE, "Analytics short arrow (right)" } },
    { "analyticsBackwardArrowLeftSegment", { 0xF7E7, "Analytics arrow (left)" } },
    { "analyticsBackwardArrowRightSegment", { 0xF7E8, "Analytics arrow segment (left)" } },
    { "analyticsBackwardArrowRightSegmentTall", { 0xF7EB, "Analytics tall arrow segment (left)" } },
    { "analyticsBackwardArrowShort", { 0xF7E6, "Analytics short arrow (left)" } },
    { "analyticsHauptrhythmusR", { 0xF4B9, "Hauptrhythmus R (Berg)" } },
    { "analyticsLongExtension", { 0xF7E3, "Analytics long extension" } },
    { "analyticsModulationCombiningBracketCenter2", { 0xF7E4, "Analytics modulation combining bracket (center)" } },
    { "analyticsModulationCombiningBracketLeft", { 0xF7E0, "Analytics modulation combining bracket (left)" } },
    { "analyticsModulationCombiningBracketRight", { 0xF7E5, "Analytics modulation combining bracket (right)" } },
    { "analyticsModulationCombiningBracketRightLong", { 0xF7E1, "Analytics modulation long combining bracket (right)" } },
    { "analyticsModulationCombiningBracketRightShort", { 0xF7E2, "Analytics modulation short combining bracket (right)" } },
    { "arpeggioArrowDownLong", { 0xF775, "Arpeggio arrow down long" } },
    { "arpeggioArrowDownMedium", { 0xF774, "Arpeggio arrow down medium" } },
    { "arpeggioArrowDownShort", { 0xF773, "Arpeggio arrow down short" } },
    { "arpeggioArrowUpLong", { 0xF772, "Arpeggio arrow up long" } },
    { "arpeggioArrowUpMedium", { 0xF771, "Arpeggio arrow up medium" } },
    { "arpeggioArrowUpShort", { 0xF770, "Arpeggio arrow up short" } },
    { "arpeggioVerticalSegment ", { 0xF700, "Arpeggio vertical segment " } },
    { "arrowDownLong", { 0xF77B, "Arrow down long" } },
    { "arrowDownMedium", { 0xF77A, "Arrow down medium" } },
    { "arrowDownShort", { 0xF779, "Arrow down short" } },
    { "arrowUpLong", { 0xF778, "Arrow up long" } },
    { "arrowUpMedium", { 0xF777, "Arrow up medium" } },
    { "arrowUpShort", { 0xF776, "Arrow up short" } },
    { "articAccentAboveLegacy", { 0xF632, "Accent above (legacy)" } },
    { "articAccentStaccatoAboveLegacy", { 0xF62B, "Accent-staccato above (legacy)" } },
    { "articAccentStaccatoBelowLegacy", { 0xF62C, "Accent-staccato below (legacy)" } },
    { "articMarcatoStaccatoAboveLegacy", { 0xF62D, "Marcato-staccato above (legacy)" } },
    { "articMarcatoStaccatoBelowLegacy", { 0xF62E, "Marcato-staccato below (legacy)" } },
    { "articTenutoAccentAboveLegacy", { 0xF630, "Tenuto-accent above (legacy)" } },
    { "articTenutoAccentBelowLegacy", { 0xF631, "Tenuto-accent below (legacy)" } },
    { "articTenutoStaccatoAboveLegacy", { 0xF62F, "Tenuto-staccato above (legacy)" } },
    { "articTenutoStaccatoBelowLegacy", { 0xF636, "Tenuto-staccato below (legacy)" } },
    { "braceFlat", { 0xF403, "Brace (flat)" } },
    { "braceLarge", { 0xF401, "Brace (large)" } },
    { "braceLarger", { 0xF402, "Brace (larger)" } },
    { "braceSmall", { 0xF400, "Brace (small)" } },
    { "brassFallRoughShortMedDecline", { 0xF764, "Brass fall rough short med decline" } },
    { "brassFallRoughShortSlightDecline", { 0xF762, "Brass fall rough short slight decline" } },
    { "brassFallRoughVeryShortFastDecline", { 0xF760, "Brass fall rough very short fast decline" } },
    { "brassFallRoughVeryShortMedDecline", { 0xF75C, "Brass fall rough very short med decline" } },
    { "brassFallRoughVeryShortSlightDecilne", { 0xF75A, "Brass fall rough very short slight decilne" } },
    { "brassFallSlight", { 0xF768, "Brass fall slight" } },
    { "brassFallSmoothVeryLong", { 0xF758, "Brass fall smooth very long" } },
    { "brassLiftShortMedIncline", { 0xF763, "Brass lift short med incline" } },
    { "brassLiftShortSlightIncline", { 0xF761, "Brass lift short slight incline" } },
    { "brassLiftSlight", { 0xF767, "Brass lift slight" } },
    { "brassLiftSmoothVeryLong", { 0xF757, "Brass lift smooth very long" } },
    { "brassLiftVeryShortMedIncline", { 0xF75B, "Brass lift very short med incline" } },
    { "brassLiftVeryShortSlightIncline", { 0xF759, "Brass lift very short slight incline" } },
    { "brassShakeLong", { 0xF756, "Brass shake long" } },
    { "brassVeryLiftShort", { 0xF75F, "Brass lift very short" } },
    { "breathMarkCommaLegacy", { 0xF635, "Breath mark comma (legacy)" } },
    { "cClefFrench", { 0xF408, "C clef (French, 18th century)" } },
    { "cClefSmall", { 0xF473, "C clef (small staff)" } },
    { "chord#11", { 0xF898, "Chord #11" } },
    { "chord#11#9", { 0xF89F, "Chord #11/#9" } },
    { "chord#11b9", { 0xF89E, "Chord #11/b9" } },
    { "chord#5", { 0xF896, "Chord #5" } },
    { "chord#9", { 0xF897, "Chord #9" } },
    { "chord#9b13", { 0xF89C, "Chord #9/b13" } },
    { "chord#9b5", { 0xF89A, "Chord #9/b5" } },
    { "chord#9b9", { 0xF89D, "Chord #9/b9" } },
    { "chord+7", { 0xF87D, "Chord +7" } },
    { "chord+7#9", { 0xF87C, "Chord +7(#9)" } },
    { "chord+7b9", { 0xF866, "Chord +7(b9)" } },
    { "chord+9", { 0xF87E, "Chord +9" } },
    { "chord+M7", { 0xF87F, "Chord +(M7)" } },
    { "chord+M9", { 0xF880, "Chord +(M9)" } },
    { "chord-11", { 0xF858, "Chord -11" } },
    { "chord-11M7", { 0xF862, "Chord -11(M7)" } },
    { "chord-11b5", { 0xF85C, "Chord -11(b5)" } },
    { "chord-11b9b5", { 0xF85F, "Chord -11(b9/b5)" } },
    { "chord-13", { 0xF859, "Chord -13" } },
    { "chord-13#11", { 0xF85D, "Chord -13(#11)" } },
    { "chord-6", { 0xF854, "Chord -6" } },
    { "chord-69", { 0xF855, "Chord -6/9" } },
    { "chord-69#11", { 0xF864, "Chord -6/9(#11)" } },
    { "chord-7", { 0xF856, "Chord -7" } },
    { "chord-7b5", { 0xF85A, "Chord -7(b5)" } },
    { "chord-7b9b5", { 0xF85E, "Chord -7(b9/b5)" } },
    { "chord-9", { 0xF857, "Chord -9" } },
    { "chord-9M7", { 0xF861, "Chord -9(M7)" } },
    { "chord-9M7#11", { 0xF863, "Chord -9(M7/#11)" } },
    { "chord-9b5", { 0xF85B, "Chord -9(b5)" } },
    { "chord-Add2", { 0xF865, "Chord -(add2)" } },
    { "chord-M7", { 0xF860, "Chord -(M7)" } },
    { "chord0", { 0xF8CB, "Chord 0" } },
    { "chord1", { 0xF8CC, "Chord 1" } },
    { "chord11", { 0xF8D5, "Chord 11" } },
    { "chord13", { 0xF8D6, "Chord 13" } },
    { "chord13#11", { 0xF87A, "Chord 13(#11)" } },
    { "chord13#9", { 0xF878, "Chord 13(#9)" } },
    { "chord13b5", { 0xF876, "Chord 13(b5)" } },
    { "chord13b9", { 0xF877, "Chord 13(b9)" } },
    { "chord13b9b5", { 0xF879, "Chord 13(b9/b5)" } },
    { "chord2", { 0xF8CD, "Chord 2" } },
    { "chord3", { 0xF8CE, "Chord 3" } },
    { "chord4", { 0xF8CF, "Chord 4" } },
    { "chord5", { 0xF8D0, "Chord 5" } },
    { "chord6", { 0xF8D1, "Chord 6" } },
    { "chord69", { 0xF83B, "Chord 6/9" } },
    { "chord69#11", { 0xF844, "Chord 6/9(#11)" } },
    { "chord7", { 0xF8D2, "Chord 7" } },
    { "chord7#11", { 0xF86C, "Chord 7(#11)" } },
    { "chord7#11#9", { 0xF872, "Chord 7(#11/#9)" } },
    { "chord7#11#9Alt", { 0xF882, "Chord 7(#11/#9) (alternate)" } },
    { "chord7#11b9", { 0xF871, "Chord 7 (#11/b9)" } },
    { "chord7#5", { 0xF86D, "Chord 7(#5)" } },
    { "chord7#9", { 0xF868, "Chord 7(#9)" } },
    { "chord7#9#5", { 0xF87B, "Chord 7(#9/#5)" } },
    { "chord7#9b13", { 0xF86A, "Chord 7(#9/b13)" } },
    { "chord7#9b5", { 0xF86F, "Chord 7(#9/b5)" } },
    { "chord7#9b9", { 0xF870, "Chord 7(#9/b9)" } },
    { "chord7Alt", { 0xF890, "Chord 7alt" } },
    { "chord7Sus", { 0xF84D, "Chord 7sus" } },
    { "chord7Sus4", { 0xF84F, "Chord 7sus4" } },
    { "chord7Sus4b9", { 0xF850, "Chord 7sus4(b9)" } },
    { "chord7Sus4b9Add3", { 0xF851, "Chord 7sus4(b9)(add3)" } },
    { "chord7b5", { 0xF86B, "Chord 7(b5)" } },
    { "chord7b9", { 0xF867, "Chord 7(b9)" } },
    { "chord7b9#5", { 0xF883, "Chord 7(b9/#5)" } },
    { "chord7b9b13", { 0xF869, "Chord 7(b9/b13)" } },
    { "chord7b9b5", { 0xF86E, "Chord7(b9/b5)" } },
    { "chord8", { 0xF8D3, "Chord 8" } },
    { "chord9", { 0xF8D4, "Chord 9" } },
    { "chord9#11", { 0xF874, "Chord 9(#11)" } },
    { "chord9#5", { 0xF875, "Chord 9(#5)" } },
    { "chord9Sus", { 0xF84E, "Chord 9sus" } },
    { "chord9b5", { 0xF873, "Chord 9(b5)" } },
    { "chordAdd11", { 0xF8C7, "Chord add11" } },
    { "chordAdd2", { 0xF8C4, "Chord add2" } },
    { "chordAdd3", { 0xF8C5, "Chord add3" } },
    { "chordAdd9", { 0xF8C6, "Chord add9" } },
    { "chordAug", { 0xF881, "Chord aug" } },
    { "chordD", { 0xF886, "Chord d (diminished)" } },
    { "chordD7", { 0xF887, "Chord d7 (diminished)" } },
    { "chordD7#9", { 0xF889, "Chord d7(#9) (diminished)" } },
    { "chordD7b9", { 0xF888, "Chord d7(b9) (diminished)" } },
    { "chordDM7", { 0xF88B, "Chord d(M7) (diminished)" } },
    { "chordDim", { 0xF884, "Chord dim" } },
    { "chordDim7", { 0xF885, "Chord dim7" } },
    { "chordDimM7", { 0xF88A, "Chord dim(M7)" } },
    { "chordH-d", { 0xF88C, "Chord half-diminished" } },
    { "chordH-d7", { 0xF88D, "Chord half-diminished7" } },
    { "chordLydian", { 0xF853, "Chord lydian" } },
    { "chordM13", { 0xF83F, "Chord m13" } },
    { "chordM13#11", { 0xF845, "Chord m13(#11)" } },
    { "chordM6", { 0xF83C, "Chord m6" } },
    { "chordM69", { 0xF840, "Chord m6/9" } },
    { "chordM69#11", { 0xF843, "Chord m6/9(#11)" } },
    { "chordM7", { 0xF83D, "Chord M7" } },
    { "chordM7#11", { 0xF841, "Chord M7/#11" } },
    { "chordM7#11Alt", { 0xF8A0, "Chord M7/#11 (alternate)" } },
    { "chordM7#5", { 0xF847, "Chord M7(#5)" } },
    { "chordM7b5", { 0xF846, "Chord M7(b5)" } },
    { "chordM9", { 0xF83E, "Chord M9" } },
    { "chordM9#11", { 0xF842, "Chord M9(#11)" } },
    { "chordM9#5", { 0xF849, "Chord M9(#5)" } },
    { "chordM9b5", { 0xF848, "Chord M9(b5)" } },
    { "chordMa", { 0xF8A2, "Chord ma (major)" } },
    { "chordMa13", { 0xF8A6, "Chord ma13" } },
    { "chordMa13#11", { 0xF8AA, "Chord ma13(#11)" } },
    { "chordMa6", { 0xF8A3, "Chord ma6" } },
    { "chordMa69", { 0xF8CA, "Chord ma6/9" } },
    { "chordMa69#11", { 0xF8A9, "Chord ma6/9(#11)" } },
    { "chordMa7", { 0xF8A4, "Chord ma7" } },
    { "chordMa7#11", { 0xF8A7, "Chord ma7(#11)" } },
    { "chordMa7#5", { 0xF8AC, "Chord ma7(#5)" } },
    { "chordMa7b5", { 0xF8AB, "Chord ma7(b5)" } },
    { "chordMa9", { 0xF8A5, "Chord ma9" } },
    { "chordMa9#11", { 0xF8A8, "Chord ma9(#11)" } },
    { "chordMa9#5", { 0xF8AE, "Chord ma9(#5)" } },
    { "chordMa9b5", { 0xF8AD, "Chord ma9(b5)" } },
    { "chordMaj", { 0xF8A1, "Chord maj" } },
    { "chordMajorTriad", { 0xF88E, "Chord major triad" } },
    { "chordMajorTriadb5", { 0xF88F, "Chord major triad (b5)" } },
    { "chordMi", { 0xF8B1, "Chord mi (minor)" } },
    { "chordMi11", { 0xF8B6, "Chord mi11" } },
    { "chordMi11M7", { 0xF8C0, "Chord mi11(M7)" } },
    { "chordMi11b5", { 0xF8BA, "Chord mi11(b5)" } },
    { "chordMi11b9b5", { 0xF8BD, "Chord mi11(b9/b5)" } },
    { "chordMi13", { 0xF8B7, "Chord mi13" } },
    { "chordMi13#11", { 0xF8BB, "Chord mi13(#11)" } },
    { "chordMi6", { 0xF8B2, "Chord mi6" } },
    { "chordMi69", { 0xF8B3, "Chord mi6/9" } },
    { "chordMi69#11", { 0xF8C2, "Chord mi6/9(#11)" } },
    { "chordMi7", { 0xF8B4, "Chord mi7" } },
    { "chordMi7b5", { 0xF8B8, "Chord mi7(b5)" } },
    { "chordMi7b9b5", { 0xF8BC, "Chord mi7(b9/b5)" } },
    { "chordMi9", { 0xF8B5, "Chord mi9" } },
    { "chordMi9M7", { 0xF8BF, "Chord mi9(M7)" } },
    { "chordMi9M7#11", { 0xF8C1, "Chord mi9(M7/#11)" } },
    { "chordMi9b5", { 0xF8B9, "Chord mi9(b5)" } },
    { "chordMiAdd2", { 0xF8C3, "Chord mi(add2)" } },
    { "chordMiM7", { 0xF8BE, "Chord mi(M7)" } },
    { "chordMin", { 0xF8B0, "Chord min" } },
    { "chordNo3rd", { 0xF8C8, "Chord no 3rd" } },
    { "chordNo5", { 0xF8C9, "Chord no 5th" } },
    { "chordOmit3", { 0xF892, "Chord omit 3" } },
    { "chordOmit5", { 0xF891, "Chord omit 5" } },
    { "chordSus", { 0xF84A, "Chord sus" } },
    { "chordSus2", { 0xF852, "Chord sus2" } },
    { "chordSus4", { 0xF84B, "Chord sus4" } },
    { "chordSus4b9", { 0xF84C, "Chord sus4(b9)" } },
    { "chordb5", { 0xF895, "Chord b5" } },
    { "chordb9", { 0xF893, "Chord b9" } },
    { "chordb9b13", { 0xF89B, "Chord b9/b13" } },
    { "chordb9b5", { 0xF899, "Chord b9/b5" } },
    { "chordm7alt", { 0xF894, "Chord M7 (alternate)" } },
    { "chorus1st", { 0xF7C4, "Chorus 1st" } },
    { "chorus2nd", { 0xF7C5, "Chorus 2nd" } },
    { "chorus3rd", { 0xF7C6, "Chorus 3rd" } },
    { "chorus4th", { 0xF7C7, "Chorus 4th" } },
    { "codaJapanese", { 0xF405, "Coda (Japanese style, serif)" } },
    { "conductorBeat2SimpleLegacy1", { 0xF7BB, "Conductor beat 2 simple (legacy 1)" } },
    { "conductorBeat2SimpleLegacy2", { 0xF7BC, "Conductor beat 2 simple (legacy 2)" } },
    { "conductorBeat3SimpleLegacy", { 0xF7BD, "Conductor beat 3 simple (legacy)" } },
    { "doubleTongueAboveNoSlur", { 0xF42D, "Double-tongue above (no slur)" } },
    { "doubleTongueBelowNoSlur", { 0xF42E, "Double-tongue below (no slur)" } },
    { "dynamicCrescendoHairpinLong", { 0xF750, "Dynamic crescendo hairpin long" } },
    { "dynamicCrescendoHairpinVeryLong", { 0xF752, "Dynamic crescendo hairpin very long" } },
    { "dynamicDiminuendoHairpinLong", { 0xF751, "Dynamic diminuendo hairpin long" } },
    { "dynamicDiminuendoHairpinVeryLong", { 0xF753, "Dynamic diminuendo hairpin very long" } },
    { "dynamicSforzandoLegacy", { 0xF610, "Dynamic sforzando (legacy)" } },
    { "enclosureBracketExtension", { 0xF721, "Enclosure bracket extension" } },
    { "enclosureBracketExtensionLong", { 0xF73C, "Enclosure bracket extension long" } },
    { "enclosureBracketExtensionShort", { 0xF727, "Enclosure bracket extension short" } },
    { "enclosureBracketLeft", { 0xF720, "Enclosure bracket left" } },
    { "enclosureBracketLeftLong", { 0xF729, "Enclosure bracket left long" } },
    { "enclosureBracketLeftShort", { 0xF728, "Enclosure bracket left short" } },
    { "enclosureBracketLongExtension", { 0xF72A, "Enclosure bracket long extension" } },
    { "enclosureBracketRight", { 0xF722, "Enclosure bracket right" } },
    { "enclosureBracketRightLong", { 0xF72B, "Enclosure bracket right long" } },
    { "enclosureBracketWavyLeft", { 0xF73B, "Enclosure bracket wavy left" } },
    { "enclosureBracketWavyLeftLong", { 0xF73E, "Enclosure bracket wavy left long" } },
    { "enclosureBracketWavyRight", { 0xF73D, "Enclosure bracket wavy right" } },
    { "enclosureBracketWavyRightLong", { 0xF740, "Enclosure bracket wavy right long" } },
    { "enclosureClosed", { 0xF74A, "Enclosure closed" } },
    { "enclosureClosedLong", { 0xF74B, "Enclosure closed long" } },
    { "enclosureParenOverExtension", { 0xF724, "Enclosure paren over extension" } },
    { "enclosureParenOverExtension2", { 0xF742, "Enclosure paren over extension 2" } },
    { "enclosureParenOverExtension2Long", { 0xF745, "Enclosure paren over extension 2 long" } },
    { "enclosureParenOverExtensionLong", { 0xF726, "Enclosure paren over extension long" } },
    { "enclosureParenOverExtensionLongAlt", { 0xF72D, "Enclosure paren over extension long alt" } },
    { "enclosureParenOverLeft", { 0xF723, "Enclosure paren over left" } },
    { "enclosureParenOverLeft2", { 0xF72C, "Enclosure paren over left 2" } },
    { "enclosureParenOverLeft2Alt", { 0xF741, "Enclosure paren over left 2 alt" } },
    { "enclosureParenOverLeft2Long", { 0xF744, "Enclosure paren over left 2 long" } },
    { "enclosureParenOverRight", { 0xF725, "Enclosure paren over right" } },
    { "enclosureParenOverRight2", { 0xF72E, "Enclosure paren over right 2" } },
    { "enclosureParenOverRight2Alt", { 0xF743, "Enclosure paren over right 2 alt" } },
    { "enclosureParenOverRight2Long", { 0xF746, "Enclosure paren over right 2 long" } },
    { "enclosureParenUnderlineExtension", { 0xF736, "Enclosure paren underline extension" } },
    { "enclosureParenUnderlineExtensionAlt", { 0xF748, "Enclosure paren underline extension alt" } },
    { "enclosureParenUnderlineExtensionLong", { 0xF739, "Enclosure paren underline extension long" } },
    { "enclosureParenUnderlineLeft", { 0xF72F, "Enclosure paren underline left" } },
    { "enclosureParenUnderlineLeftAlt", { 0xF735, "Enclosure paren underline left alt" } },
    { "enclosureParenUnderlineLeftAlt2", { 0xF747, "Enclosure paren underline left alt 2" } },
    { "enclosureParenUnderlineLeftLong", { 0xF732, "Enclosure paren underline left long" } },
    { "enclosureParenUnderlineLeftLongAlt", { 0xF738, "Enclosure paren underline left long alt" } },
    { "enclosureParenUnderlineRight", { 0xF731, "Enclosure paren underline right" } },
    { "enclosureParenUnderlineRightLong", { 0xF734, "Enclosure paren underline right long" } },
    { "enclosureParenUnderlineRightShort", { 0xF737, "Enclosure paren underline right short" } },
    { "enclosureParenUnderlineRightShortAlt2", { 0xF749, "Enclosure paren underline right short alt 2" } },
    { "enclosureParenUnderlineRightShortLong", { 0xF73A, "Enclosure paren underline right short long" } },
    { "enclosureRehersalA", { 0xF821, "Enclosure rehersal a" } },
    { "enclosureRehersalB", { 0xF822, "Enclosure rehersal b" } },
    { "enclosureRehersalC", { 0xF823, "Enclosure rehersal c" } },
    { "enclosureRehersalD", { 0xF824, "Enclosure rehersal d" } },
    { "enclosureRehersalE", { 0xF825, "Enclosure rehersal e" } },
    { "enclosureRehersalF", { 0xF826, "Enclosure rehersal f" } },
    { "enclosureRehersalG", { 0xF827, "Enclosure rehersal g" } },
    { "enclosureRehersalH", { 0xF828, "Enclosure rehersal h" } },
    { "enclosureRehersalI", { 0xF829, "Enclosure rehersal i" } },
    { "enclosureRehersalJenclosureRehersalK", { 0xF82A, "Enclosure rehersal jenclosure rehersal k" } },
    { "enclosureRehersalK", { 0xF82B, "Enclosure rehersal k" } },
    { "enclosureRehersalL", { 0xF82C, "Enclosure rehersal l" } },
    { "enclosureRehersalM", { 0xF82D, "Enclosure rehersal m" } },
    { "enclosureRehersalN", { 0xF82E, "Enclosure rehersal n" } },
    { "enclosureRehersalO", { 0xF82F, "Enclosure rehersal o" } },
    { "enclosureRehersalP", { 0xF830, "Enclosure rehersal p" } },
    { "enclosureRehersalQ", { 0xF831, "Enclosure rehersal q" } },
    { "enclosureRehersalR", { 0xF832, "Enclosure rehersal r" } },
    { "enclosureRehersalS", { 0xF833, "Enclosure rehersal s" } },
    { "enclosureRehersalT", { 0xF834, "Enclosure rehersal t" } },
    { "enclosureRehersalU", { 0xF835, "Enclosure rehersal u" } },
    { "enclosureRehersalW", { 0xF837, "Enclosure rehersal w" } },
    { "enclosureRehersalX", { 0xF838, "Enclosure rehersal x" } },
    { "enclosureRehersalY", { 0xF839, "Enclosure rehersal y" } },
    { "enclosureRehersalZ", { 0xF83A, "Enclosure rehersal z" } },
    { "enclosureRehersalenclosureRehersalA", { 0xF836, "Enclosure rehersalenclosure rehersal a" } },
    { "enclosureUnderlineExtension", { 0xF730, "Enclosure underline extension" } },
    { "enclosureUnderlineLong", { 0xF733, "Enclosure underline long" } },
    { "fClef19thCentury", { 0xF407, "F clef (19th century)" } },
    { "fClef5Below", { 0xF532, "F clef (5 below)" } },
    { "fClefAlt1", { 0xF7D8, "F clef alt 1" } },
    { "fClefFrench", { 0xF406, "F clef (French, 18th century)" } },
    { "fClefSmall", { 0xF474, "F clef (small staff)" } },
    { "fine", { 0xF7C8, "Fine" } },
    { "flag1024thDownStraight", { 0xF426, "Combining flag 8 (1024th) below (straight)" } },
    { "flag1024thUpStraight", { 0xF424, "Combining flag 8 (1024th) above (straight)" } },
    { "flag128thDownStraight", { 0xF41D, "Combining flag 5 (128th) below (straight)" } },
    { "flag128thUpStraight", { 0xF41B, "Combining flag 5 (128th) above (straight)" } },
    { "flag16thDownAlt", { 0xF705, "Flag 16th down alt" } },
    { "flag16thDownStraight", { 0xF414, "Combining flag 2 (16th) below (straight)" } },
    { "flag16thUpAlt", { 0xF703, "Flag 16th up alt" } },
    { "flag16thUpStraight", { 0xF412, "Combining flag 2 (16th) above (straight)" } },
    { "flag256thDownStraight", { 0xF420, "Combining flag 6 (256th) below (straight)" } },
    { "flag256thUpStraight", { 0xF41E, "Combining flag 6 (256th) above (straight)" } },
    { "flag32ndDownStraight", { 0xF417, "Combining flag 3 (32nd) below (straight)" } },
    { "flag32ndUpStraight", { 0xF415, "Combining flag 3 (32nd) above (straight)" } },
    { "flag512thDownStraight", { 0xF423, "Combining flag 7 (512th) below (straight)" } },
    { "flag512thUpStraight", { 0xF421, "Combining flag 7 (512th) above (straight)" } },
    { "flag64thDownStraight", { 0xF41A, "Combining flag 4 (64th) below (straight)" } },
    { "flag64thUpStraight", { 0xF418, "Combining flag 4 (64th) above (straight)" } },
    { "flag8thDownAlt", { 0xF704, "Flag 8th down alt" } },
    { "flag8thDownAlt2", { 0xF769, "Flag 8th down alt 2" } },
    { "flag8thDownStraight", { 0xF411, "Combining flag 1 (8th) below (straight)" } },
    { "flag8thUpAlt2", { 0xF701, "Flag 8th up alt 2" } },
    { "flag8thUpAlt3", { 0xF702, "Flag 8th up alt 3" } },
    { "flag8thUpStraight", { 0xF40F, "Combining flag 1 (8th) above (straight)" } },
    { "fretboard6StringLegacy", { 0xF8FE, "Fretboard 6 string (legacy)" } },
    { "gClef0Below", { 0xF533, "G Clef (0 below)" } },
    { "gClef10Below", { 0xF534, "G Clef (10 below)" } },
    { "gClef11Below", { 0xF535, "G Clef (11 below)" } },
    { "gClef12Below", { 0xF536, "G Clef (12 below)" } },
    { "gClef13Below", { 0xF537, "G Clef (13 below)" } },
    { "gClef14Below", { 0xF538, "G Clef (14 below)" } },
    { "gClef15Below", { 0xF539, "G Clef (15 below)" } },
    { "gClef16Below", { 0xF53A, "G Clef (16 below)" } },
    { "gClef17Below", { 0xF53B, "G Clef (17 below)" } },
    { "gClef2Above", { 0xF53C, "G Clef (2 above)" } },
    { "gClef2Below", { 0xF53D, "G Clef (2 below)" } },
    { "gClef3Above", { 0xF53E, "G Clef (3 above)" } },
    { "gClef3Below", { 0xF53F, "G Clef (3 below)" } },
    { "gClef4Above", { 0xF540, "G Clef (4 above)" } },
    { "gClef4Below", { 0xF541, "G Clef (4 below)" } },
    { "gClef5Above", { 0xF542, "G Clef (5 above)" } },
    { "gClef5Below", { 0xF543, "G Clef (5 below)" } },
    { "gClef6Above", { 0xF544, "G Clef (6 above)" } },
    { "gClef6Below", { 0xF545, "G Clef (6 below)" } },
    { "gClef7Above", { 0xF546, "G Clef (7 above)" } },
    { "gClef7Below", { 0xF547, "G Clef (7 below)" } },
    { "gClef8Above", { 0xF548, "G Clef (8 above)" } },
    { "gClef8Below", { 0xF549, "G Clef (8 below)" } },
    { "gClef9Above", { 0xF54A, "G Clef (9 above)" } },
    { "gClef9Below", { 0xF54B, "G Clef (9 below)" } },
    { "gClefAlt", { 0xF7D7, "G clef alt" } },
    { "gClefAlt2", { 0xF7D9, "G clef alt 2" } },
    { "gClefAlt3", { 0xF7DA, "G clef alt 3" } },
    { "gClefAlt4", { 0xF7DB, "G clef alt 4" } },
    { "gClefFlat10Below", { 0xF54C, "G Clef (flat 10 below)" } },
    { "gClefFlat11Below", { 0xF54D, "G Clef (flat 11 below)" } },
    { "gClefFlat13Below", { 0xF54E, "G Clef (flat 13 below)" } },
    { "gClefFlat14Below", { 0xF54F, "G Clef (flat 14 below)" } },
    { "gClefFlat15Below", { 0xF550, "G Clef (flat 15 below)" } },
    { "gClefFlat16Below", { 0xF551, "G Clef (flat 16 below)" } },
    { "gClefFlat1Below", { 0xF552, "G Clef (flat 1 below)" } },
    { "gClefFlat2Above", { 0xF553, "G Clef (flat 2 above)" } },
    { "gClefFlat2Below", { 0xF554, "G Clef (flat 2 below)" } },
    { "gClefFlat3Above", { 0xF555, "G Clef (flat 3 above)" } },
    { "gClefFlat3Below", { 0xF556, "G Clef (flat 3 below)" } },
    { "gClefFlat4Below", { 0xF557, "G Clef (flat 4 below)" } },
    { "gClefFlat5Above", { 0xF558, "G Clef (flat 5 above)" } },
    { "gClefFlat6Above", { 0xF559, "G Clef (flat 6 above)" } },
    { "gClefFlat6Below", { 0xF55A, "G Clef (flat 6 below)" } },
    { "gClefFlat7Above", { 0xF55B, "G Clef (flat 7 above)" } },
    { "gClefFlat7Below", { 0xF55C, "G Clef (flat 7 below)" } },
    { "gClefFlat8Above", { 0xF55D, "G Clef (flat 8 above)" } },
    { "gClefFlat9Above", { 0xF55E, "G Clef (flat 9 above)" } },
    { "gClefFlat9Below", { 0xF55F, "G Clef (flat 9 below)" } },
    { "gClefNat2Below", { 0xF560, "G Clef (natural 2 below)" } },
    { "gClefNatural10Below", { 0xF561, "G Clef (natural 10 below)" } },
    { "gClefNatural13Below", { 0xF562, "G Clef (natural 13 below)" } },
    { "gClefNatural17Below", { 0xF563, "G Clef (natural 17 below)" } },
    { "gClefNatural2Above", { 0xF564, "G Clef (natural 2 above)" } },
    { "gClefNatural3Above", { 0xF565, "G Clef (natural 3 above)" } },
    { "gClefNatural3Below", { 0xF566, "G Clef (natural 3 below)" } },
    { "gClefNatural6Above", { 0xF567, "G Clef (natural 6 above)" } },
    { "gClefNatural6Below", { 0xF568, "G Clef (natural 6 below)" } },
    { "gClefNatural7Above", { 0xF569, "G Clef (natural 7 above)" } },
    { "gClefNatural9Above", { 0xF56A, "G Clef (natural 9 above)" } },
    { "gClefNatural9Below", { 0xF56B, "G Clef (natural 9 below)" } },
    { "gClefSharp12Below", { 0xF56C, "G Clef (sharp 12 below)" } },
    { "gClefSharp1Above", { 0xF56D, "G Clef (sharp 1 above)" } },
    { "gClefSharp4Above", { 0xF56E, "G Clef (sharp 4 above)" } },
    { "gClefSharp5Below", { 0xF56F, "G Clef (sharp 5 below)" } },
    { "gClefSmall", { 0xF472, "G clef (small staff)" } },
    { "guitarGolpeFlamenco", { 0xF4B8, "Golpe (tapping the pick guard) (Vounelakos)" } },
    { "handbellsEcho1Alt", { 0xF687, "Handbells echo 1 alt" } },
    { "handbellsGyroAlt", { 0xF688, "Handbells gyro alt" } },
    { "harpMetalRodAlt", { 0xF436, "Metal rod pictogram (alternative)" } },
    { "harpTuningKeyAlt", { 0xF437, "Tuning key pictogram (alternative)" } },
    { "keyboardPedalPedNoDot", { 0xF434, "Pedal mark (no dot)" } },
    { "keyboardPedalSostNoDot", { 0xF435, "Sostenuto pedal mark (no dot)" } },
    { "laissezVibrer", { 0xF765, "Laissez vibrer" } },
    { "legacyX", { 0xF820, "x (legacy)" } },
    { "mensuralProportion4Old", { 0xF43D, "Mensural proportion 4 (old)" } },
    { "metSwing", { 0xF74F, "Met swing" } },
    { "miscCodaLogo", { 0xF7C3, "Coda logo" } },
    { "miscCodaMonk", { 0xF7C2, "Coda guitar monk" } },
    { "miscEyeglassesAlt1", { 0xF685, "Eyeglasses 1.0" } },
    { "miscEyeglassesAlt2", { 0xF686, "Eyeglasses 2.0" } },
    { "miscLegacy1", { 0xF7C1, "Misc (legacy 1)" } },
    { "miscLegacy2", { 0xF7CD, "Misc (legacy 2)" } },
    { "miscLegacy3", { 0xF7CE, "Misc (legacy 3)" } },
    { "note16thDownWide", { 0xF60C, "Note 16th down wide" } },
    { "note16thUpWide", { 0xF60B, "Note 16th up wide" } },
    { "note64thUpAlt", { 0xF7CC, "Note 64th up alt" } },
    { "note8thDownWide", { 0xF60A, "Note 8th down wide" } },
    { "note8thUpWide", { 0xF609, "Note 8th up wide" } },
    { "noteHalfDownWide", { 0xF606, "Note half down wide" } },
    { "noteHalfUpWide", { 0xF605, "Note half up wide" } },
    { "noteQuarterDownSmall", { 0xF707, "Note quarter down small" } },
    { "noteQuarterDownWide", { 0xF608, "Note quarter down wide" } },
    { "noteQuarterUpSmall", { 0xF706, "Note quarter up small" } },
    { "noteQuarterUpWide", { 0xF607, "Note quarter up wide" } },
    { "noteheadBlackDouble", { 0xF782, "Notehead black double" } },
    { "noteheadBlackLV1", { 0xF795, "Notehead black l v1" } },
    { "noteheadBlackLV2", { 0xF796, "Notehead black l v2" } },
    { "noteheadBlackLV3", { 0xF797, "Notehead black l v3" } },
    { "noteheadBlackLV4", { 0xF798, "Notehead black l v4" } },
    { "noteheadBlackLV5", { 0xF799, "Notehead black l v5" } },
    { "noteheadBlackLV6", { 0xF79A, "Notehead black l v6" } },
    { "noteheadBlackLV7", { 0xF79B, "Notehead black l v7" } },
    { "noteheadBlackLV8", { 0xF79C, "Notehead black l v8" } },
    { "noteheadBlackLV9", { 0xF79D, "Notehead black l v9" } },
    { "noteheadBlackLVLegacy", { 0xF8D9, "Notehead black l v (legacy)" } },
    { "noteheadBlackParens", { 0xF5D1, "Closed notehead (parentheses)" } },
    { "noteheadBlackParenthesisLVLegacy", { 0xF8EA, "Notehead black parenthesis l v (legacy)" } },
    { "noteheadBlackWide", { 0xF604, "Notehead black wide" } },
    { "noteheadCircleX1LVLegacy", { 0xF8DA, "Notehead circle x1 l v (legacy)" } },
    { "noteheadCircleX2LVLegacy", { 0xF8DB, "Notehead circle x2 l v (legacy)" } },
    { "noteheadCircleX3LVLegacy", { 0xF8DC, "Notehead circle x3 l v (legacy)" } },
    { "noteheadCircledBlackLargeLVLegacy", { 0xF8EB, "Notehead circled black large l v (legacy)" } },
    { "noteheadCircledHalfLargeLVLegacy", { 0xF8F7, "Notehead circled half large l v (legacy)" } },
    { "noteheadCircledXLargeLV1", { 0xF79E, "Notehead circled x large l v1" } },
    { "noteheadCircledXLargeLV2", { 0xF79F, "Notehead circled x large l v2" } },
    { "noteheadCircledXLargeLV3", { 0xF7A0, "Notehead circled x large l v3" } },
    { "noteheadCircledXLargeLV4", { 0xF7A1, "Notehead circled x large l v4" } },
    { "noteheadCircledXLargeLegacy", { 0xF612, "Notehead circled x large (legacy)" } },
    { "noteheadDiamondBlackLVLegacy", { 0xF8E3, "Notehead diamond black l v (legacy)" } },
    { "noteheadDiamondBlackLVLegacyAlt", { 0xF8EC, "Notehead diamond black l v (legacy alt)" } },
    { "noteheadDiamondHalfWideLVLegacy", { 0xF8F0, "Notehead diamond half wide l v (legacy)" } },
    { "noteheadDiamondWhiteLegacy", { 0xF625, "Notehead diamond white (legacy)" } },
    { "noteheadDiamondWhiteWideLegacy", { 0xF626, "Notehead diamond white wide (legacy)" } },
    { "noteheadDiamondWholeOldLVLegacy", { 0xF8F8, "Notehead diamond whole old l v (legacy)" } },
    { "noteheadDoubleWholeAlt", { 0xF40E, "Double whole note (breve), single vertical strokes" } },
    { "noteheadDoubleWholeAlt2", { 0xF43F, "Notehead double whole alt 2" } },
    { "noteheadDoubleWholeAltLongWings", { 0xF68A, "Notehead double whole alt long wings" } },
    { "noteheadDoubleWholeAltWide", { 0xF601, "Notehead double whole alt wide" } },
    { "noteheadDoubleWholeLongWings", { 0xF689, "Notehead double whole long wings" } },
    { "noteheadDoubleWholeParens", { 0xF5D4, "Double whole notehead (parentheses)" } },
    { "noteheadDoubleWholeWide", { 0xF600, "Notehead double whole wide" } },
    { "noteheadHalfDouble", { 0xF781, "Notehead half double" } },
    { "noteheadHalfLV1", { 0xF78C, "Notehead half l v1" } },
    { "noteheadHalfLV2", { 0xF78D, "Notehead half l v2" } },
    { "noteheadHalfLV3", { 0xF78E, "Notehead half l v3" } },
    { "noteheadHalfLV4", { 0xF78F, "Notehead half l v4" } },
    { "noteheadHalfLV5", { 0xF790, "Notehead half l v5" } },
    { "noteheadHalfLV6", { 0xF791, "Notehead half l v6" } },
    { "noteheadHalfLV7", { 0xF792, "Notehead half l v7" } },
    { "noteheadHalfLV8", { 0xF793, "Notehead half l v8" } },
    { "noteheadHalfLV9", { 0xF794, "Notehead half l v9" } },
    { "noteheadHalfLVLegacy", { 0xF8D8, "Notehead half l v (legacy)" } },
    { "noteheadHalfParens", { 0xF5D2, "Half notehead (parentheses)" } },
    { "noteheadHalfWide", { 0xF603, "Notehead half wide" } },
    { "noteheadMoonBlackLVLegacy", { 0xF8E2, "Notehead moon black l v (legacy)" } },
    { "noteheadMoonWhiteLVLegacy", { 0xF8EE, "Notehead moon white l v (legacy)" } },
    { "noteheadMoonWhiteLegacy", { 0xF61B, "Notehead moon white (legacy)" } },
    { "noteheadParenthesisAlt", { 0xF74C, "Notehead parenthesis alt" } },
    { "noteheadPlusBlackLVLegacy", { 0xF8ED, "Notehead plus black l v (legacy)" } },
    { "noteheadPlusBlackLegacy", { 0xF627, "Notehead plus black (legacy)" } },
    { "noteheadRoundWhiteLVLegacy", { 0xF8FB, "Notehead round white l v (legacy)" } },
    { "noteheadRoundWhiteLegacy", { 0xF629, "Notehead round white (legacy)" } },
    { "noteheadSlashDiamondWhiteLVLegacy", { 0xF8FC, "Notehead slash diamond white l v (legacy)" } },
    { "noteheadSlashHorizontalEndsLegacy", { 0xF673, "Notehead slash horizontal ends (legacy)" } },
    { "noteheadSlashVerticalEndsLegacy", { 0xF628, "Notehead slash vertical ends (legacy)" } },
    { "noteheadSlashWhiteWholeLegacy", { 0xF7AA, "Notehead slash white whole (legacy)" } },
    { "noteheadSquareBlackLVLegacy", { 0xF8E0, "Notehead square black l v (legacy)" } },
    { "noteheadSquareBlackLVLegacyAlt", { 0xF8E5, "Notehead square black l v (legacy alt)" } },
    { "noteheadSquareBlackLegacy", { 0xF615, "Notehead square black (legacy)" } },
    { "noteheadSquareWhiteAltLVLegacy", { 0xF8F4, "Notehead square white alt l v (legacy)" } },
    { "noteheadSquareWhiteLVLegacy", { 0xF8F9, "Notehead square white l v (legacy)" } },
    { "noteheadSquareWhiteLegacy", { 0xF613, "Notehead square white (legacy)" } },
    { "noteheadSquareWhiteLegacy2", { 0xF614, "Notehead square white (legacy 2)" } },
    { "noteheadSquareWhiteLegacy3", { 0xF624, "Notehead square white (legacy 3)" } },
    { "noteheadTriangleBlackLVLegacy", { 0xF8E1, "Notehead triangle black l v (legacy)" } },
    { "noteheadTriangleDownBlackLVLegacy", { 0xF8E9, "Notehead triangle down black l v (legacy)" } },
    { "noteheadTriangleDownWhiteLVLegacy", { 0xF8FA, "Notehead triangle down white l v (legacy)" } },
    { "noteheadTriangleDownWhiteLegacy", { 0xF617, "Notehead triangle down white (legacy)" } },
    { "noteheadTriangleLeftBlackLVLegacy", { 0xF8E7, "Notehead triangle left black l v (legacy)" } },
    { "noteheadTriangleLeftWhiteLVLegacy", { 0xF8F5, "Notehead triangle left white l v (legacy)" } },
    { "noteheadTriangleLeftWhiteLegacy", { 0xF618, "Notehead triangle left white (legacy)" } },
    { "noteheadTriangleRightBlackLVLegacy", { 0xF8E8, "Notehead triangle right black l v (legacy)" } },
    { "noteheadTriangleRightWhiteLVLegacy", { 0xF8F3, "Notehead triangle right white l v (legacy)" } },
    { "noteheadTriangleRightWhiteLegacy", { 0xF619, "Notehead triangle right white (legacy)" } },
    { "noteheadTriangleRoundDownBlackLVLegacy", { 0xF8E6, "Notehead triangle round down black l v (legacy)" } },
    { "noteheadTriangleRoundDownWhiteLVLegacy", { 0xF8F2, "Notehead triangle round down white l v (legacy)" } },
    { "noteheadTriangleRoundDownWhiteLegacy", { 0xF61C, "Notehead triangle round down white (legacy)" } },
    { "noteheadTriangleUpRightBlackLVLegacy", { 0xF8E4, "Notehead triangle up right black l v (legacy)" } },
    { "noteheadTriangleUpRightWhiteLVLegacy", { 0xF8F1, "Notehead triangle up right white l v (legacy)" } },
    { "noteheadTriangleUpRightWhiteLegacy", { 0xF61A, "Notehead triangle up right white (legacy)" } },
    { "noteheadTriangleUpWhiteLVLegacy", { 0xF8EF, "Notehead triangle up white l v (legacy)" } },
    { "noteheadTriangleUpWhiteLegacy", { 0xF616, "Notehead triangle up white (legacy)" } },
    { "noteheadVoidWithXLV1", { 0xF7A2, "Notehead void with x l v1" } },
    { "noteheadVoidWithXLV2", { 0xF7A3, "Notehead void with x l v2" } },
    { "noteheadVoidWithXLV3", { 0xF7A4, "Notehead void with x l v3" } },
    { "noteheadVoidWithXLV4", { 0xF7A5, "Notehead void with x l v4" } },
    { "noteheadVoidWithXLV5", { 0xF7A6, "Notehead void with x l v5" } },
    { "noteheadVoidWithXLV6", { 0xF7A7, "Notehead void with x l v6" } },
    { "noteheadVoidWithXLV7", { 0xF7A8, "Notehead void with x l v7" } },
    { "noteheadVoidWithXLV8", { 0xF7A9, "Notehead void with x l v8" } },
    { "noteheadWhiteParenthesisLVLegacy", { 0xF8F6, "Notehead white parenthesis l v (legacy)" } },
    { "noteheadWholeLV1", { 0xF783, "Notehead whole l v1" } },
    { "noteheadWholeLV2", { 0xF784, "Notehead whole l v2" } },
    { "noteheadWholeLV3", { 0xF785, "Notehead whole l v3" } },
    { "noteheadWholeLV4", { 0xF786, "Notehead whole l v4" } },
    { "noteheadWholeLV5", { 0xF787, "Notehead whole l v5" } },
    { "noteheadWholeLV6", { 0xF788, "Notehead whole l v6" } },
    { "noteheadWholeLV7", { 0xF789, "Notehead whole l v7" } },
    { "noteheadWholeLV8", { 0xF78A, "Notehead whole l v8" } },
    { "noteheadWholeLV9", { 0xF78B, "Notehead whole l v9" } },
    { "noteheadWholeLVJazz", { 0xF8D7, "Notehead whole l v jazz" } },
    { "noteheadWholeParens", { 0xF5D3, "Whole notehead (parentheses)" } },
    { "noteheadWholeWide", { 0xF602, "Notehead whole wide" } },
    { "noteheadXBlack1LVLegacy", { 0xF8DD, "Notehead x black1 l v (legacy)" } },
    { "noteheadXBlack2LVLegacy", { 0xF8DE, "Notehead x black2 l v (legacy)" } },
    { "noteheadXBlack3LVLegacy", { 0xF8DF, "Notehead x black3 l v (legacy)" } },
    { "noteheadXBlackLegacy", { 0xF611, "Notehead x black (legacy)" } },
    { "noteheadXLV1", { 0xF7AC, "Notehead x l v1" } },
    { "noteheadXLV2", { 0xF7AD, "Notehead x l v2" } },
    { "noteheadXLV3", { 0xF7AE, "Notehead x l v3" } },
    { "noteheadXLV4", { 0xF7AF, "Notehead x l v4" } },
    { "noteheadXLV5", { 0xF7B0, "Notehead x l v5" } },
    { "noteheadXLV6", { 0xF7B1, "Notehead x l v6" } },
    { "noteheadXLV7", { 0xF7B2, "Notehead x l v7" } },
    { "noteheadXLV8", { 0xF7B3, "Notehead x l v8" } },
    { "noteheadwholeDouble", { 0xF780, "Noteheadwhole double" } },
    { "ornamentTrillFlatAbove", { 0xF5B2, "Trill (flat above)" } },
    { "ornamentTrillFlatAboveLegacy", { 0xF68C, "Trill flat above (legacy)" } },
    { "ornamentTrillNaturalAbove", { 0xF5B3, "Trill (Natural above)" } },
    { "ornamentTrillNaturalAboveLegacy", { 0xF68D, "Trill natural above (legacy)" } },
    { "ornamentTrillSharpAbove", { 0xF5B4, "Trill (sharp above)" } },
    { "ornamentTrillSharpAboveLegacy", { 0xF68E, "Trill sharp above (legacy)" } },
    { "ornamentTurnFlatAbove", { 0xF5B5, "Turn (flat above)" } },
    { "ornamentTurnFlatAboveSharpBelow", { 0xF5B6, "Turn (flat above, sharp below)" } },
    { "ornamentTurnFlatBelow", { 0xF5B7, "Turn (flat below)" } },
    { "ornamentTurnNaturalAbove", { 0xF5B8, "Turn (natural above)" } },
    { "ornamentTurnNaturalBelow", { 0xF5B9, "Turn (natural below)" } },
    { "ornamentTurnSharpAbove", { 0xF5BA, "Turn (sharp above)" } },
    { "ornamentTurnSharpAboveFlatBelow", { 0xF5BB, "Turn (sharp above, flat below)" } },
    { "ornamentTurnSharpBelow", { 0xF5BC, "Turn (sharp below)" } },
    { "ottavaAltaLegacy", { 0xF677, "Ottava alta (legacy)" } },
    { "ottavaBassaBaLegacy", { 0xF679, "Ottava bassa ba (legacy)" } },
    { "ottavaBassaVbLegacy", { 0xF678, "Ottava bassa vb (legacy)" } },
    { "ottavaLegacy", { 0xF676, "Ottava (legacy)" } },
    { "pictBassDrumPeinkofer", { 0xF4AF, "Bass drum (Peinkofer/Tannigel)" } },
    { "pictBongosPeinkofer", { 0xF4B0, "Bongos (Peinkofer/Tannigel)" } },
    { "pictCastanetsSmithBrindle", { 0xF439, "Castanets (Smith Brindle)" } },
    { "pictCongaPeinkofer", { 0xF4B1, "Conga (Peinkofer/Tannigel)" } },
    { "pictCowBellBerio", { 0xF43B, "Cow bell (Berio)" } },
    { "pictFlexatonePeinkofer", { 0xF4B6, "Flexatone (Peinkofer/Tannigel)" } },
    { "pictGlspPeinkofer", { 0xF4AA, "Glockenspiel (Peinkofer/Tannigel)" } },
    { "pictGuiroPeinkofer", { 0xF4B5, "Guiro (Peinkofer/Tannigel)" } },
    { "pictGuiroSevsay", { 0xF4B4, "Guiro (Sevsay)" } },
    { "pictHalfOpen2Legacy", { 0xF62A, "Pict half open 2 (legacy)" } },
    { "pictLithophonePeinkofer", { 0xF4A7, "Lithophone (Peinkofer/Tannigel)" } },
    { "pictLotusFlutePeinkofer", { 0xF4AC, "Lotus flute (Peinkofer/Tannigel)" } },
    { "pictMarPeinkofer", { 0xF4AB, "Marimba (Peinkofer/Tannigel)" } },
    { "pictMaracaSmithBrindle", { 0xF43C, "Maraca (Smith Brindle)" } },
    { "pictMusicalSawPeinkofer", { 0xF4B7, "Musical saw (Peinkofer/Tannigel)" } },
    { "pictSleighBellSmithBrindle", { 0xF43A, "Sleigh bell (Smith Brindle)" } },
    { "pictTambourineStockhausen", { 0xF438, "Tambourine (Stockhausen)" } },
    { "pictTimbalesPeinkofer", { 0xF4B3, "Timbales (Peinkofer/Tannigel)" } },
    { "pictTimpaniPeinkofer", { 0xF4AE, "Timpani (Peinkofer/Tannigel)" } },
    { "pictTomTomChinesePeinkofer", { 0xF4AD, "Chinese tom-tom (Peinkofer/Tannigel)" } },
    { "pictTomTomPeinkofer", { 0xF4B2, "Tom-tom (Peinkofer/Tannigel)" } },
    { "pictTubaphonePeinkofer", { 0xF4A8, "Tubaphone (Peinkofer/Tannigel)" } },
    { "pictVibMotorOffPeinkofer", { 0xF4A6, "Metallophone (vibraphone motor off) (Peinkofer/Tannigel)" } },
    { "pictVibPeinkofer", { 0xF4A5, "Vibraphone (Peinkofer/Tannigel)" } },
    { "pictXylBassPeinkofer", { 0xF4A3, "Bass xylophone (Peinkofer/Tannigel)" } },
    { "pictXylPeinkofer", { 0xF4A9, "Xylophone (Peinkofer/Tannigel)" } },
    { "pictXylTenorPeinkofer", { 0xF4A4, "Tenor xylophone (Peinkofer/Tannigel)" } },
    { "pluckedSnapPizzicatoAboveGerman", { 0xF433, "Snap pizzicato above (German)" } },
    { "pluckedSnapPizzicatoBelowGerman", { 0xF432, "Snap pizzicato below (German)" } },
    { "quindicesimaBassaMbLegacy", { 0xF67C, "Quindicesima bassa mb (legacy)" } },
    { "quindicesimaLegacy", { 0xF67A, "Quindicesima (legacy)" } },
    { "quindicesimaLegacy2", { 0xF67B, "Quindicesima (legacy 2)" } },
    { "repeat1BarLegacy", { 0xF674, "Repeat 1 bar (legacy)" } },
    { "repeat2BarLegacy", { 0xF675, "Repeat 2 bar (legacy)" } },
    { "repeatRightLeftThick", { 0xF45C, "Right and left repeat sign (thick-thick)" } },
    { "restHBarAngled", { 0xF766, "Rest h bar angled" } },
    { "restQuarterAlt1", { 0xF7DC, "Rest quarter alt 1" } },
    { "restWholeLegacy", { 0xF670, "Rest whole (legacy)" } },
    { "segnoJapanese", { 0xF404, "Segno (Japanese style, rotated)" } },
    { "stringsChangeBowDirectionImposed", { 0xF43E, "Change bow direction, indeterminate (Plötz)" } },
    { "stringsChangeBowDirectionLiga", { 0xF431, "Change bow direction, indeterminate (Pricope)" } },
    { "stringsDownBowLegacy", { 0xF634, "Strings down bow (legacy)" } },
    { "stringsUpBowLegacy", { 0xF633, "Strings up bow (legacy)" } },
    { "textBlackNoteFrac16thLongBeam", { 0xF7D4, "Text black note frac 16th long beam" } },
    { "textBlackNoteFrac32ndLongBeam", { 0xF7D5, "Text black note frac 32nd long beam" } },
    { "textBlackNoteFrac8thLongBeam", { 0xF7D3, "Text black note frac 8th long beam" } },
    { "textBlackNoteFracSingle16th", { 0xF7D6, "Text black note frac single 16th" } },
    { "textBlackNoteMiddleTripletNote", { 0xF7CB, "Text black note middle triplet note" } },
    { "textBlackNoteRightFacing16thBeam", { 0xF7CA, "Text black note right facing 16th beam" } },
    { "textEnclosureCurvedArrow", { 0xF814, "Text enclosure curved arrow" } },
    { "textEnclosureCurvedArrowWHook", { 0xF815, "Text enclosure curved arrow w hook" } },
    { "textEnclosureExtensionShort", { 0xF817, "Text enclosure extension short" } },
    { "textEnclosureFine", { 0xF81F, "Text enclosure fine" } },
    { "textEnclosureSegmentArrow", { 0xF813, "Text enclosure segment arrow" } },
    { "textEnclosureSegmentArrowDown", { 0xF81E, "Text enclosure segment arrow down" } },
    { "textEnclosureSegmentArrowJogDown", { 0xF81D, "Text enclosure segment arrow jog down" } },
    { "textEnclosureSegmentArrowJogOver", { 0xF81C, "Text enclosure segment arrow jog over" } },
    { "textEnclosureSegmentArrowJogUp", { 0xF81B, "Text enclosure segment arrow jog up" } },
    { "textEnclosureSegmentCUrvedArrowShort", { 0xF819, "Text enclosure segment c urved arrow short" } },
    { "textEnclosureSegmentCurvedArrowLong", { 0xF81A, "Text enclosure segment curved arrow long" } },
    { "textEnclosureSegmentExtension", { 0xF812, "Text enclosure segment extension" } },
    { "textEnclosureSegmentExtensionLong", { 0xF818, "Text enclosure segment extension long" } },
    { "textEnclosureSegmentJogDown", { 0xF810, "Text enclosure segment jog down" } },
    { "textEnclosureSegmentJogUp", { 0xF811, "Text enclosure segment jog up" } },
    { "textEnclosureSegmentLeftHook", { 0xF816, "Text enclosure segment left hook" } },
    { "textTripletBracketFull", { 0xF7D2, "Text triplet bracket full" } },
    { "timeSig0Large", { 0xF440, "Time signature 0 (outside staff)" } },
    { "timeSig1Large", { 0xF441, "Time signature 1 (outside staff)" } },
    { "timeSig2Large", { 0xF442, "Time signature 2 (outside staff)" } },
    { "timeSig3Large", { 0xF443, "Time signature 3 (outside staff)" } },
    { "timeSig4Large", { 0xF444, "Time signature 4 (outside staff)" } },
    { "timeSig5Large", { 0xF445, "Time signature 5 (outside staff)" } },
    { "timeSig6Large", { 0xF446, "Time signature 6 (outside staff)" } },
    { "timeSig7Large", { 0xF447, "Time signature 7 (outside staff)" } },
    { "timeSig8Large", { 0xF448, "Time signature 8 (outside staff)" } },
    { "timeSig9Large", { 0xF449, "Time signature 9 (outside staff)" } },
    { "timeSigCommonLarge", { 0xF44A, "Common time (outside staff)" } },
    { "timeSigCutCommonLarge", { 0xF44B, "Cut time (outside staff)" } },
    { "timeSigPlusLarge", { 0xF44C, "Time signature + (outside staff)" } },
    { "tremolo1Alt", { 0xF680, "Tremolo 1 alt" } },
    { "tremolo2Alt", { 0xF681, "Tremolo 2 alt" } },
    { "tremolo3Alt", { 0xF682, "Tremolo 3 alt" } },
    { "tremolo3Alt1", { 0xF7B6, "Tremolo 3 alt 1" } },
    { "tremolo3Alt2", { 0xF7B7, "Tremolo 3 alt 2" } },
    { "tremolo3Alt3", { 0xF7B8, "Tremolo 3 alt 3" } },
    { "tremolo3Alt4", { 0xF7B9, "Tremolo 3 alt 4" } },
    { "tremolo3Alt5", { 0xF7BA, "Tremolo 3 alt 5" } },
    { "tremolo4Legacy", { 0xF683, "Tremolo 4 (legacy)" } },
    { "tremolo5Legacy", { 0xF684, "Tremolo 5 (legacy)" } },
    { "tripleTongueAboveNoSlur", { 0xF42F, "Triple-tongue above (no slur)" } },
    { "tripleTongueBelowNoSlur", { 0xF430, "Triple-tongue below (no slur)" } },
    { "unpitchedPercussionClef1Alt", { 0xF409, "Unpitched percussion clef 1 (thick-thin)" } },
    { "ventiduesimaAltaLegacy", { 0xF67E, "Ventiduesima alta (legacy)" } },
    { "ventiduesimaBassaMbLegacy", { 0xF67F, "Ventiduesima bassa mb (legacy)" } },
    { "ventiduesimaLegacy", { 0xF67D, "Ventiduesima (legacy)" } },
};

} // namespace musx::fontmaps::glyphnames
